/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockssi.h"

static const char* CMockString_SSIAdvDataPutFrameEnd = "SSIAdvDataPutFrameEnd";
static const char* CMockString_SSIAdvDataPutFrameEndNonBlocking = "SSIAdvDataPutFrameEndNonBlocking";
static const char* CMockString_SSIAdvFrameHoldDisable = "SSIAdvFrameHoldDisable";
static const char* CMockString_SSIAdvFrameHoldEnable = "SSIAdvFrameHoldEnable";
static const char* CMockString_SSIAdvModeSet = "SSIAdvModeSet";
static const char* CMockString_SSIBusy = "SSIBusy";
static const char* CMockString_SSIClockSourceGet = "SSIClockSourceGet";
static const char* CMockString_SSIClockSourceSet = "SSIClockSourceSet";
static const char* CMockString_SSIConfigSetExpClk = "SSIConfigSetExpClk";
static const char* CMockString_SSIDMADisable = "SSIDMADisable";
static const char* CMockString_SSIDMAEnable = "SSIDMAEnable";
static const char* CMockString_SSIDataGet = "SSIDataGet";
static const char* CMockString_SSIDataGetNonBlocking = "SSIDataGetNonBlocking";
static const char* CMockString_SSIDataPut = "SSIDataPut";
static const char* CMockString_SSIDataPutNonBlocking = "SSIDataPutNonBlocking";
static const char* CMockString_SSIDisable = "SSIDisable";
static const char* CMockString_SSIEnable = "SSIEnable";
static const char* CMockString_SSIIntClear = "SSIIntClear";
static const char* CMockString_SSIIntEnable = "SSIIntEnable";
static const char* CMockString_SSIIntRegister = "SSIIntRegister";
static const char* CMockString_SSIIntStatus = "SSIIntStatus";
static const char* CMockString_SSIIntUnregister = "SSIIntUnregister";
static const char* CMockString_bMasked = "bMasked";
static const char* CMockString_pfnHandler = "pfnHandler";
static const char* CMockString_pui32Data = "pui32Data";
static const char* CMockString_ui32Base = "ui32Base";
static const char* CMockString_ui32BitRate = "ui32BitRate";
static const char* CMockString_ui32DMAFlags = "ui32DMAFlags";
static const char* CMockString_ui32Data = "ui32Data";
static const char* CMockString_ui32DataWidth = "ui32DataWidth";
static const char* CMockString_ui32IntFlags = "ui32IntFlags";
static const char* CMockString_ui32Mode = "ui32Mode";
static const char* CMockString_ui32Protocol = "ui32Protocol";
static const char* CMockString_ui32SSIClk = "ui32SSIClk";
static const char* CMockString_ui32Source = "ui32Source";

typedef struct _CMOCK_SSIConfigSetExpClk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32SSIClk;
  uint32_t Expected_ui32Protocol;
  uint32_t Expected_ui32Mode;
  uint32_t Expected_ui32BitRate;
  uint32_t Expected_ui32DataWidth;

} CMOCK_SSIConfigSetExpClk_CALL_INSTANCE;

typedef struct _CMOCK_SSIDataGet_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t* Expected_pui32Data;
  int ReturnThruPtr_pui32Data_Used;
  uint32_t* ReturnThruPtr_pui32Data_Val;
  int ReturnThruPtr_pui32Data_Size;

} CMOCK_SSIDataGet_CALL_INSTANCE;

typedef struct _CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int32_t ReturnVal;
  uint32_t Expected_ui32Base;
  uint32_t* Expected_pui32Data;
  int ReturnThruPtr_pui32Data_Used;
  uint32_t* ReturnThruPtr_pui32Data_Val;
  int ReturnThruPtr_pui32Data_Size;

} CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE;

typedef struct _CMOCK_SSIDataPut_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Data;

} CMOCK_SSIDataPut_CALL_INSTANCE;

typedef struct _CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int32_t ReturnVal;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Data;

} CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE;

typedef struct _CMOCK_SSIDisable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;

} CMOCK_SSIDisable_CALL_INSTANCE;

typedef struct _CMOCK_SSIEnable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;

} CMOCK_SSIEnable_CALL_INSTANCE;

typedef struct _CMOCK_SSIIntClear_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32IntFlags;

} CMOCK_SSIIntClear_CALL_INSTANCE;

typedef struct _CMOCK_SSIIntEnable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32IntFlags;

} CMOCK_SSIIntEnable_CALL_INSTANCE;

typedef struct _CMOCK_SSIIntRegister_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  cmock_ssi_func_ptr1 Expected_pfnHandler;

} CMOCK_SSIIntRegister_CALL_INSTANCE;

typedef struct _CMOCK_SSIIntStatus_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t ReturnVal;
  uint32_t Expected_ui32Base;
  bool Expected_bMasked;

} CMOCK_SSIIntStatus_CALL_INSTANCE;

typedef struct _CMOCK_SSIIntUnregister_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;

} CMOCK_SSIIntUnregister_CALL_INSTANCE;

typedef struct _CMOCK_SSIDMAEnable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32DMAFlags;

} CMOCK_SSIDMAEnable_CALL_INSTANCE;

typedef struct _CMOCK_SSIDMADisable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32DMAFlags;

} CMOCK_SSIDMADisable_CALL_INSTANCE;

typedef struct _CMOCK_SSIBusy_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  bool ReturnVal;
  uint32_t Expected_ui32Base;

} CMOCK_SSIBusy_CALL_INSTANCE;

typedef struct _CMOCK_SSIClockSourceSet_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Source;

} CMOCK_SSIClockSourceSet_CALL_INSTANCE;

typedef struct _CMOCK_SSIClockSourceGet_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t ReturnVal;
  uint32_t Expected_ui32Base;

} CMOCK_SSIClockSourceGet_CALL_INSTANCE;

typedef struct _CMOCK_SSIAdvModeSet_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Mode;

} CMOCK_SSIAdvModeSet_CALL_INSTANCE;

typedef struct _CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Data;

} CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE;

typedef struct _CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  int32_t ReturnVal;
  uint32_t Expected_ui32Base;
  uint32_t Expected_ui32Data;

} CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE;

typedef struct _CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;

} CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE;

typedef struct _CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  CMOCK_ARG_MODE IgnoreMode;
  uint32_t Expected_ui32Base;

} CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE;

static struct MockssiInstance
{
  int SSIConfigSetExpClk_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIConfigSetExpClk_CallInstance;
  int SSIDataGet_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIDataGet_CallInstance;
  int SSIDataGetNonBlocking_IgnoreBool;
  int32_t SSIDataGetNonBlocking_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIDataGetNonBlocking_CallInstance;
  int SSIDataPut_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIDataPut_CallInstance;
  int SSIDataPutNonBlocking_IgnoreBool;
  int32_t SSIDataPutNonBlocking_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIDataPutNonBlocking_CallInstance;
  int SSIDisable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIDisable_CallInstance;
  int SSIEnable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIEnable_CallInstance;
  int SSIIntClear_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIIntClear_CallInstance;
  int SSIIntEnable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIIntEnable_CallInstance;
  int SSIIntRegister_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIIntRegister_CallInstance;
  int SSIIntStatus_IgnoreBool;
  uint32_t SSIIntStatus_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIIntStatus_CallInstance;
  int SSIIntUnregister_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIIntUnregister_CallInstance;
  int SSIDMAEnable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIDMAEnable_CallInstance;
  int SSIDMADisable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIDMADisable_CallInstance;
  int SSIBusy_IgnoreBool;
  bool SSIBusy_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIBusy_CallInstance;
  int SSIClockSourceSet_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIClockSourceSet_CallInstance;
  int SSIClockSourceGet_IgnoreBool;
  uint32_t SSIClockSourceGet_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIClockSourceGet_CallInstance;
  int SSIAdvModeSet_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIAdvModeSet_CallInstance;
  int SSIAdvDataPutFrameEnd_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIAdvDataPutFrameEnd_CallInstance;
  int SSIAdvDataPutFrameEndNonBlocking_IgnoreBool;
  int32_t SSIAdvDataPutFrameEndNonBlocking_FinalReturn;
  CMOCK_MEM_INDEX_TYPE SSIAdvDataPutFrameEndNonBlocking_CallInstance;
  int SSIAdvFrameHoldEnable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIAdvFrameHoldEnable_CallInstance;
  int SSIAdvFrameHoldDisable_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSIAdvFrameHoldDisable_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockssi_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.SSIConfigSetExpClk_IgnoreBool)
    Mock.SSIConfigSetExpClk_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIConfigSetExpClk);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIConfigSetExpClk_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDataGet_IgnoreBool)
    Mock.SSIDataGet_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDataGet);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDataGet_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDataGetNonBlocking_IgnoreBool)
    Mock.SSIDataGetNonBlocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDataGetNonBlocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDataGetNonBlocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDataPut_IgnoreBool)
    Mock.SSIDataPut_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDataPut);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDataPut_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDataPutNonBlocking_IgnoreBool)
    Mock.SSIDataPutNonBlocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDataPutNonBlocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDataPutNonBlocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDisable_IgnoreBool)
    Mock.SSIDisable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDisable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDisable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIEnable_IgnoreBool)
    Mock.SSIEnable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIEnable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIEnable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIIntClear_IgnoreBool)
    Mock.SSIIntClear_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIIntClear);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIIntClear_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIIntEnable_IgnoreBool)
    Mock.SSIIntEnable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIIntEnable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIIntEnable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIIntRegister_IgnoreBool)
    Mock.SSIIntRegister_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIIntRegister);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIIntRegister_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIIntStatus_IgnoreBool)
    Mock.SSIIntStatus_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIIntStatus);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIIntStatus_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIIntUnregister_IgnoreBool)
    Mock.SSIIntUnregister_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIIntUnregister);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIIntUnregister_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDMAEnable_IgnoreBool)
    Mock.SSIDMAEnable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDMAEnable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDMAEnable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIDMADisable_IgnoreBool)
    Mock.SSIDMADisable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIDMADisable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIDMADisable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIBusy_IgnoreBool)
    Mock.SSIBusy_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIBusy);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIBusy_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIClockSourceSet_IgnoreBool)
    Mock.SSIClockSourceSet_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIClockSourceSet);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIClockSourceSet_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIClockSourceGet_IgnoreBool)
    Mock.SSIClockSourceGet_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIClockSourceGet);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIClockSourceGet_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIAdvModeSet_IgnoreBool)
    Mock.SSIAdvModeSet_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIAdvModeSet);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIAdvModeSet_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIAdvDataPutFrameEnd_IgnoreBool)
    Mock.SSIAdvDataPutFrameEnd_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIAdvDataPutFrameEnd);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIAdvDataPutFrameEnd_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool)
    Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIAdvDataPutFrameEndNonBlocking);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIAdvFrameHoldEnable_IgnoreBool)
    Mock.SSIAdvFrameHoldEnable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIAdvFrameHoldEnable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIAdvFrameHoldEnable_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSIAdvFrameHoldDisable_IgnoreBool)
    Mock.SSIAdvFrameHoldDisable_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSIAdvFrameHoldDisable);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSIAdvFrameHoldDisable_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockssi_Init(void)
{
  Mockssi_Destroy();
}

void Mockssi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SSIConfigSetExpClk(uint32_t ui32Base, uint32_t ui32SSIClk, uint32_t ui32Protocol, uint32_t ui32Mode, uint32_t ui32BitRate, uint32_t ui32DataWidth)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIConfigSetExpClk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIConfigSetExpClk);
  cmock_call_instance = (CMOCK_SSIConfigSetExpClk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIConfigSetExpClk_CallInstance);
  Mock.SSIConfigSetExpClk_CallInstance = CMock_Guts_MemNext(Mock.SSIConfigSetExpClk_CallInstance);
  if (Mock.SSIConfigSetExpClk_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32SSIClk);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32SSIClk, ui32SSIClk, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32Protocol);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Protocol, ui32Protocol, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32Mode);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Mode, ui32Mode, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32BitRate);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32BitRate, ui32BitRate, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIConfigSetExpClk,CMockString_ui32DataWidth);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32DataWidth, ui32DataWidth, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIConfigSetExpClk(CMOCK_SSIConfigSetExpClk_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32SSIClk, uint32_t ui32Protocol, uint32_t ui32Mode, uint32_t ui32BitRate, uint32_t ui32DataWidth)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32SSIClk = ui32SSIClk;
  cmock_call_instance->Expected_ui32Protocol = ui32Protocol;
  cmock_call_instance->Expected_ui32Mode = ui32Mode;
  cmock_call_instance->Expected_ui32BitRate = ui32BitRate;
  cmock_call_instance->Expected_ui32DataWidth = ui32DataWidth;
}

void SSIConfigSetExpClk_CMockIgnore(void)
{
  Mock.SSIConfigSetExpClk_IgnoreBool = (int)1;
}

void SSIConfigSetExpClk_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIConfigSetExpClk_CALL_INSTANCE));
  CMOCK_SSIConfigSetExpClk_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIConfigSetExpClk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIConfigSetExpClk_CallInstance = CMock_Guts_MemChain(Mock.SSIConfigSetExpClk_CallInstance, cmock_guts_index);
  Mock.SSIConfigSetExpClk_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIConfigSetExpClk_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32SSIClk, uint32_t ui32Protocol, uint32_t ui32Mode, uint32_t ui32BitRate, uint32_t ui32DataWidth)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIConfigSetExpClk_CALL_INSTANCE));
  CMOCK_SSIConfigSetExpClk_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIConfigSetExpClk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIConfigSetExpClk_CallInstance = CMock_Guts_MemChain(Mock.SSIConfigSetExpClk_CallInstance, cmock_guts_index);
  Mock.SSIConfigSetExpClk_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIConfigSetExpClk(cmock_call_instance, ui32Base, ui32SSIClk, ui32Protocol, ui32Mode, ui32BitRate, ui32DataWidth);
  UNITY_CLR_DETAILS();
}

void SSIDataGet(uint32_t ui32Base, uint32_t* pui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDataGet_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDataGet);
  cmock_call_instance = (CMOCK_SSIDataGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDataGet_CallInstance);
  Mock.SSIDataGet_CallInstance = CMock_Guts_MemNext(Mock.SSIDataGet_CallInstance);
  if (Mock.SSIDataGet_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDataGet,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDataGet,CMockString_pui32Data);
    if (cmock_call_instance->Expected_pui32Data == NULL)
      { UNITY_TEST_ASSERT_NULL(pui32Data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pui32Data, pui32Data, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ReturnThruPtr_pui32Data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pui32Data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pui32Data, (void*)cmock_call_instance->ReturnThruPtr_pui32Data_Val,
      cmock_call_instance->ReturnThruPtr_pui32Data_Size);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIDataGet(CMOCK_SSIDataGet_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t* pui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_pui32Data = pui32Data;
  cmock_call_instance->ReturnThruPtr_pui32Data_Used = 0;
}

void SSIDataGet_CMockIgnore(void)
{
  Mock.SSIDataGet_IgnoreBool = (int)1;
}

void SSIDataGet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataGet_CALL_INSTANCE));
  CMOCK_SSIDataGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataGet_CallInstance = CMock_Guts_MemChain(Mock.SSIDataGet_CallInstance, cmock_guts_index);
  Mock.SSIDataGet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDataGet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t* pui32Data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataGet_CALL_INSTANCE));
  CMOCK_SSIDataGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataGet_CallInstance = CMock_Guts_MemChain(Mock.SSIDataGet_CallInstance, cmock_guts_index);
  Mock.SSIDataGet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDataGet(cmock_call_instance, ui32Base, pui32Data);
  UNITY_CLR_DETAILS();
}

void SSIDataGet_CMockReturnMemThruPtr_pui32Data(UNITY_LINE_TYPE cmock_line, uint32_t* pui32Data, int cmock_size)
{
  CMOCK_SSIDataGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SSIDataGet_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pui32Data_Used = 1;
  cmock_call_instance->ReturnThruPtr_pui32Data_Val = pui32Data;
  cmock_call_instance->ReturnThruPtr_pui32Data_Size = cmock_size;
}

int32_t SSIDataGetNonBlocking(uint32_t ui32Base, uint32_t* pui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDataGetNonBlocking);
  cmock_call_instance = (CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDataGetNonBlocking_CallInstance);
  Mock.SSIDataGetNonBlocking_CallInstance = CMock_Guts_MemNext(Mock.SSIDataGetNonBlocking_CallInstance);
  if (Mock.SSIDataGetNonBlocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIDataGetNonBlocking_FinalReturn;
    Mock.SSIDataGetNonBlocking_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDataGetNonBlocking,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDataGetNonBlocking,CMockString_pui32Data);
    if (cmock_call_instance->Expected_pui32Data == NULL)
      { UNITY_TEST_ASSERT_NULL(pui32Data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pui32Data, pui32Data, 1, cmock_line, CMockStringMismatch); }
  }
  }
  if (cmock_call_instance->ReturnThruPtr_pui32Data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pui32Data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pui32Data, (void*)cmock_call_instance->ReturnThruPtr_pui32Data_Val,
      cmock_call_instance->ReturnThruPtr_pui32Data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIDataGetNonBlocking(CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t* pui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_pui32Data = pui32Data;
  cmock_call_instance->ReturnThruPtr_pui32Data_Used = 0;
}

void SSIDataGetNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataGetNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataGetNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataGetNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIDataGetNonBlocking_IgnoreBool = (int)1;
}

void SSIDataGetNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataGetNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataGetNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataGetNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDataGetNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t* pui32Data, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataGetNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataGetNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataGetNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDataGetNonBlocking(cmock_call_instance, ui32Base, pui32Data);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIDataGetNonBlocking_CMockReturnMemThruPtr_pui32Data(UNITY_LINE_TYPE cmock_line, uint32_t* pui32Data, int cmock_size)
{
  CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataGetNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.SSIDataGetNonBlocking_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pui32Data_Used = 1;
  cmock_call_instance->ReturnThruPtr_pui32Data_Val = pui32Data;
  cmock_call_instance->ReturnThruPtr_pui32Data_Size = cmock_size;
}

void SSIDataPut(uint32_t ui32Base, uint32_t ui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDataPut_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDataPut);
  cmock_call_instance = (CMOCK_SSIDataPut_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDataPut_CallInstance);
  Mock.SSIDataPut_CallInstance = CMock_Guts_MemNext(Mock.SSIDataPut_CallInstance);
  if (Mock.SSIDataPut_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDataPut,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDataPut,CMockString_ui32Data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Data, ui32Data, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIDataPut(CMOCK_SSIDataPut_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Data = ui32Data;
}

void SSIDataPut_CMockIgnore(void)
{
  Mock.SSIDataPut_IgnoreBool = (int)1;
}

void SSIDataPut_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataPut_CALL_INSTANCE));
  CMOCK_SSIDataPut_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataPut_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataPut_CallInstance = CMock_Guts_MemChain(Mock.SSIDataPut_CallInstance, cmock_guts_index);
  Mock.SSIDataPut_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDataPut_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataPut_CALL_INSTANCE));
  CMOCK_SSIDataPut_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataPut_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataPut_CallInstance = CMock_Guts_MemChain(Mock.SSIDataPut_CallInstance, cmock_guts_index);
  Mock.SSIDataPut_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDataPut(cmock_call_instance, ui32Base, ui32Data);
  UNITY_CLR_DETAILS();
}

int32_t SSIDataPutNonBlocking(uint32_t ui32Base, uint32_t ui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDataPutNonBlocking);
  cmock_call_instance = (CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDataPutNonBlocking_CallInstance);
  Mock.SSIDataPutNonBlocking_CallInstance = CMock_Guts_MemNext(Mock.SSIDataPutNonBlocking_CallInstance);
  if (Mock.SSIDataPutNonBlocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIDataPutNonBlocking_FinalReturn;
    Mock.SSIDataPutNonBlocking_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDataPutNonBlocking,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDataPutNonBlocking,CMockString_ui32Data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Data, ui32Data, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIDataPutNonBlocking(CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Data = ui32Data;
}

void SSIDataPutNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataPutNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataPutNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataPutNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIDataPutNonBlocking_IgnoreBool = (int)1;
}

void SSIDataPutNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataPutNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataPutNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataPutNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDataPutNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE));
  CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDataPutNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDataPutNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIDataPutNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIDataPutNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDataPutNonBlocking(cmock_call_instance, ui32Base, ui32Data);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIDisable(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDisable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDisable);
  cmock_call_instance = (CMOCK_SSIDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDisable_CallInstance);
  Mock.SSIDisable_CallInstance = CMock_Guts_MemNext(Mock.SSIDisable_CallInstance);
  if (Mock.SSIDisable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDisable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIDisable(CMOCK_SSIDisable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIDisable_CMockIgnore(void)
{
  Mock.SSIDisable_IgnoreBool = (int)1;
}

void SSIDisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDisable_CALL_INSTANCE));
  CMOCK_SSIDisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDisable_CallInstance = CMock_Guts_MemChain(Mock.SSIDisable_CallInstance, cmock_guts_index);
  Mock.SSIDisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDisable_CALL_INSTANCE));
  CMOCK_SSIDisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDisable_CallInstance = CMock_Guts_MemChain(Mock.SSIDisable_CallInstance, cmock_guts_index);
  Mock.SSIDisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDisable(cmock_call_instance, ui32Base);
  UNITY_CLR_DETAILS();
}

void SSIEnable(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIEnable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIEnable);
  cmock_call_instance = (CMOCK_SSIEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIEnable_CallInstance);
  Mock.SSIEnable_CallInstance = CMock_Guts_MemNext(Mock.SSIEnable_CallInstance);
  if (Mock.SSIEnable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIEnable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIEnable(CMOCK_SSIEnable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIEnable_CMockIgnore(void)
{
  Mock.SSIEnable_IgnoreBool = (int)1;
}

void SSIEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIEnable_CALL_INSTANCE));
  CMOCK_SSIEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIEnable_CallInstance, cmock_guts_index);
  Mock.SSIEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIEnable_CALL_INSTANCE));
  CMOCK_SSIEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIEnable_CallInstance, cmock_guts_index);
  Mock.SSIEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIEnable(cmock_call_instance, ui32Base);
  UNITY_CLR_DETAILS();
}

void SSIIntClear(uint32_t ui32Base, uint32_t ui32IntFlags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIIntClear_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIIntClear);
  cmock_call_instance = (CMOCK_SSIIntClear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIIntClear_CallInstance);
  Mock.SSIIntClear_CallInstance = CMock_Guts_MemNext(Mock.SSIIntClear_CallInstance);
  if (Mock.SSIIntClear_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIIntClear,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIIntClear,CMockString_ui32IntFlags);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32IntFlags, ui32IntFlags, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIIntClear(CMOCK_SSIIntClear_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32IntFlags)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32IntFlags = ui32IntFlags;
}

void SSIIntClear_CMockIgnore(void)
{
  Mock.SSIIntClear_IgnoreBool = (int)1;
}

void SSIIntClear_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntClear_CALL_INSTANCE));
  CMOCK_SSIIntClear_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntClear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntClear_CallInstance = CMock_Guts_MemChain(Mock.SSIIntClear_CallInstance, cmock_guts_index);
  Mock.SSIIntClear_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIIntClear_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32IntFlags)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntClear_CALL_INSTANCE));
  CMOCK_SSIIntClear_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntClear_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntClear_CallInstance = CMock_Guts_MemChain(Mock.SSIIntClear_CallInstance, cmock_guts_index);
  Mock.SSIIntClear_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIIntClear(cmock_call_instance, ui32Base, ui32IntFlags);
  UNITY_CLR_DETAILS();
}

void SSIIntEnable(uint32_t ui32Base, uint32_t ui32IntFlags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIIntEnable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIIntEnable);
  cmock_call_instance = (CMOCK_SSIIntEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIIntEnable_CallInstance);
  Mock.SSIIntEnable_CallInstance = CMock_Guts_MemNext(Mock.SSIIntEnable_CallInstance);
  if (Mock.SSIIntEnable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIIntEnable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIIntEnable,CMockString_ui32IntFlags);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32IntFlags, ui32IntFlags, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIIntEnable(CMOCK_SSIIntEnable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32IntFlags)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32IntFlags = ui32IntFlags;
}

void SSIIntEnable_CMockIgnore(void)
{
  Mock.SSIIntEnable_IgnoreBool = (int)1;
}

void SSIIntEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntEnable_CALL_INSTANCE));
  CMOCK_SSIIntEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIIntEnable_CallInstance, cmock_guts_index);
  Mock.SSIIntEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIIntEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32IntFlags)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntEnable_CALL_INSTANCE));
  CMOCK_SSIIntEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIIntEnable_CallInstance, cmock_guts_index);
  Mock.SSIIntEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIIntEnable(cmock_call_instance, ui32Base, ui32IntFlags);
  UNITY_CLR_DETAILS();
}

void SSIIntRegister(uint32_t ui32Base, cmock_ssi_func_ptr1 pfnHandler)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIIntRegister_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIIntRegister);
  cmock_call_instance = (CMOCK_SSIIntRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIIntRegister_CallInstance);
  Mock.SSIIntRegister_CallInstance = CMock_Guts_MemNext(Mock.SSIIntRegister_CallInstance);
  if (Mock.SSIIntRegister_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIIntRegister,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIIntRegister,CMockString_pfnHandler);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_pfnHandler, pfnHandler, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIIntRegister(CMOCK_SSIIntRegister_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, cmock_ssi_func_ptr1 pfnHandler)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  memcpy(&cmock_call_instance->Expected_pfnHandler, &pfnHandler, sizeof(cmock_ssi_func_ptr1));
}

void SSIIntRegister_CMockIgnore(void)
{
  Mock.SSIIntRegister_IgnoreBool = (int)1;
}

void SSIIntRegister_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntRegister_CALL_INSTANCE));
  CMOCK_SSIIntRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntRegister_CallInstance = CMock_Guts_MemChain(Mock.SSIIntRegister_CallInstance, cmock_guts_index);
  Mock.SSIIntRegister_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIIntRegister_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, cmock_ssi_func_ptr1 pfnHandler)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntRegister_CALL_INSTANCE));
  CMOCK_SSIIntRegister_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntRegister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntRegister_CallInstance = CMock_Guts_MemChain(Mock.SSIIntRegister_CallInstance, cmock_guts_index);
  Mock.SSIIntRegister_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIIntRegister(cmock_call_instance, ui32Base, pfnHandler);
  UNITY_CLR_DETAILS();
}

uint32_t SSIIntStatus(uint32_t ui32Base, bool bMasked)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIIntStatus_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIIntStatus);
  cmock_call_instance = (CMOCK_SSIIntStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIIntStatus_CallInstance);
  Mock.SSIIntStatus_CallInstance = CMock_Guts_MemNext(Mock.SSIIntStatus_CallInstance);
  if (Mock.SSIIntStatus_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIIntStatus_FinalReturn;
    Mock.SSIIntStatus_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIIntStatus,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIIntStatus,CMockString_bMasked);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_bMasked, bMasked, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIIntStatus(CMOCK_SSIIntStatus_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, bool bMasked)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_bMasked = bMasked;
}

void SSIIntStatus_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntStatus_CALL_INSTANCE));
  CMOCK_SSIIntStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntStatus_CallInstance = CMock_Guts_MemChain(Mock.SSIIntStatus_CallInstance, cmock_guts_index);
  Mock.SSIIntStatus_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIIntStatus_IgnoreBool = (int)1;
}

void SSIIntStatus_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntStatus_CALL_INSTANCE));
  CMOCK_SSIIntStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntStatus_CallInstance = CMock_Guts_MemChain(Mock.SSIIntStatus_CallInstance, cmock_guts_index);
  Mock.SSIIntStatus_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIIntStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, bool bMasked, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntStatus_CALL_INSTANCE));
  CMOCK_SSIIntStatus_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntStatus_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntStatus_CallInstance = CMock_Guts_MemChain(Mock.SSIIntStatus_CallInstance, cmock_guts_index);
  Mock.SSIIntStatus_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIIntStatus(cmock_call_instance, ui32Base, bMasked);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIIntUnregister(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIIntUnregister_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIIntUnregister);
  cmock_call_instance = (CMOCK_SSIIntUnregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIIntUnregister_CallInstance);
  Mock.SSIIntUnregister_CallInstance = CMock_Guts_MemNext(Mock.SSIIntUnregister_CallInstance);
  if (Mock.SSIIntUnregister_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIIntUnregister,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIIntUnregister(CMOCK_SSIIntUnregister_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIIntUnregister_CMockIgnore(void)
{
  Mock.SSIIntUnregister_IgnoreBool = (int)1;
}

void SSIIntUnregister_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntUnregister_CALL_INSTANCE));
  CMOCK_SSIIntUnregister_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntUnregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntUnregister_CallInstance = CMock_Guts_MemChain(Mock.SSIIntUnregister_CallInstance, cmock_guts_index);
  Mock.SSIIntUnregister_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIIntUnregister_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIIntUnregister_CALL_INSTANCE));
  CMOCK_SSIIntUnregister_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIIntUnregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIIntUnregister_CallInstance = CMock_Guts_MemChain(Mock.SSIIntUnregister_CallInstance, cmock_guts_index);
  Mock.SSIIntUnregister_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIIntUnregister(cmock_call_instance, ui32Base);
  UNITY_CLR_DETAILS();
}

void SSIDMAEnable(uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDMAEnable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDMAEnable);
  cmock_call_instance = (CMOCK_SSIDMAEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDMAEnable_CallInstance);
  Mock.SSIDMAEnable_CallInstance = CMock_Guts_MemNext(Mock.SSIDMAEnable_CallInstance);
  if (Mock.SSIDMAEnable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDMAEnable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDMAEnable,CMockString_ui32DMAFlags);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32DMAFlags, ui32DMAFlags, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIDMAEnable(CMOCK_SSIDMAEnable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32DMAFlags = ui32DMAFlags;
}

void SSIDMAEnable_CMockIgnore(void)
{
  Mock.SSIDMAEnable_IgnoreBool = (int)1;
}

void SSIDMAEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDMAEnable_CALL_INSTANCE));
  CMOCK_SSIDMAEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDMAEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDMAEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIDMAEnable_CallInstance, cmock_guts_index);
  Mock.SSIDMAEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDMAEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDMAEnable_CALL_INSTANCE));
  CMOCK_SSIDMAEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDMAEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDMAEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIDMAEnable_CallInstance, cmock_guts_index);
  Mock.SSIDMAEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDMAEnable(cmock_call_instance, ui32Base, ui32DMAFlags);
  UNITY_CLR_DETAILS();
}

void SSIDMADisable(uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIDMADisable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIDMADisable);
  cmock_call_instance = (CMOCK_SSIDMADisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIDMADisable_CallInstance);
  Mock.SSIDMADisable_CallInstance = CMock_Guts_MemNext(Mock.SSIDMADisable_CallInstance);
  if (Mock.SSIDMADisable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIDMADisable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIDMADisable,CMockString_ui32DMAFlags);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32DMAFlags, ui32DMAFlags, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIDMADisable(CMOCK_SSIDMADisable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32DMAFlags = ui32DMAFlags;
}

void SSIDMADisable_CMockIgnore(void)
{
  Mock.SSIDMADisable_IgnoreBool = (int)1;
}

void SSIDMADisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDMADisable_CALL_INSTANCE));
  CMOCK_SSIDMADisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDMADisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDMADisable_CallInstance = CMock_Guts_MemChain(Mock.SSIDMADisable_CallInstance, cmock_guts_index);
  Mock.SSIDMADisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIDMADisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32DMAFlags)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIDMADisable_CALL_INSTANCE));
  CMOCK_SSIDMADisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIDMADisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIDMADisable_CallInstance = CMock_Guts_MemChain(Mock.SSIDMADisable_CallInstance, cmock_guts_index);
  Mock.SSIDMADisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIDMADisable(cmock_call_instance, ui32Base, ui32DMAFlags);
  UNITY_CLR_DETAILS();
}

bool SSIBusy(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIBusy_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIBusy);
  cmock_call_instance = (CMOCK_SSIBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIBusy_CallInstance);
  Mock.SSIBusy_CallInstance = CMock_Guts_MemNext(Mock.SSIBusy_CallInstance);
  if (Mock.SSIBusy_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIBusy_FinalReturn;
    Mock.SSIBusy_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIBusy,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIBusy(CMOCK_SSIBusy_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIBusy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIBusy_CALL_INSTANCE));
  CMOCK_SSIBusy_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIBusy_CallInstance = CMock_Guts_MemChain(Mock.SSIBusy_CallInstance, cmock_guts_index);
  Mock.SSIBusy_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIBusy_IgnoreBool = (int)1;
}

void SSIBusy_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIBusy_CALL_INSTANCE));
  CMOCK_SSIBusy_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIBusy_CallInstance = CMock_Guts_MemChain(Mock.SSIBusy_CallInstance, cmock_guts_index);
  Mock.SSIBusy_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIBusy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIBusy_CALL_INSTANCE));
  CMOCK_SSIBusy_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIBusy_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIBusy_CallInstance = CMock_Guts_MemChain(Mock.SSIBusy_CallInstance, cmock_guts_index);
  Mock.SSIBusy_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIBusy(cmock_call_instance, ui32Base);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIClockSourceSet(uint32_t ui32Base, uint32_t ui32Source)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIClockSourceSet_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIClockSourceSet);
  cmock_call_instance = (CMOCK_SSIClockSourceSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIClockSourceSet_CallInstance);
  Mock.SSIClockSourceSet_CallInstance = CMock_Guts_MemNext(Mock.SSIClockSourceSet_CallInstance);
  if (Mock.SSIClockSourceSet_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIClockSourceSet,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIClockSourceSet,CMockString_ui32Source);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Source, ui32Source, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIClockSourceSet(CMOCK_SSIClockSourceSet_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Source)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Source = ui32Source;
}

void SSIClockSourceSet_CMockIgnore(void)
{
  Mock.SSIClockSourceSet_IgnoreBool = (int)1;
}

void SSIClockSourceSet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIClockSourceSet_CALL_INSTANCE));
  CMOCK_SSIClockSourceSet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIClockSourceSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIClockSourceSet_CallInstance = CMock_Guts_MemChain(Mock.SSIClockSourceSet_CallInstance, cmock_guts_index);
  Mock.SSIClockSourceSet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIClockSourceSet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Source)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIClockSourceSet_CALL_INSTANCE));
  CMOCK_SSIClockSourceSet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIClockSourceSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIClockSourceSet_CallInstance = CMock_Guts_MemChain(Mock.SSIClockSourceSet_CallInstance, cmock_guts_index);
  Mock.SSIClockSourceSet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIClockSourceSet(cmock_call_instance, ui32Base, ui32Source);
  UNITY_CLR_DETAILS();
}

uint32_t SSIClockSourceGet(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIClockSourceGet_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIClockSourceGet);
  cmock_call_instance = (CMOCK_SSIClockSourceGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIClockSourceGet_CallInstance);
  Mock.SSIClockSourceGet_CallInstance = CMock_Guts_MemNext(Mock.SSIClockSourceGet_CallInstance);
  if (Mock.SSIClockSourceGet_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIClockSourceGet_FinalReturn;
    Mock.SSIClockSourceGet_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIClockSourceGet,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIClockSourceGet(CMOCK_SSIClockSourceGet_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIClockSourceGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIClockSourceGet_CALL_INSTANCE));
  CMOCK_SSIClockSourceGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIClockSourceGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIClockSourceGet_CallInstance = CMock_Guts_MemChain(Mock.SSIClockSourceGet_CallInstance, cmock_guts_index);
  Mock.SSIClockSourceGet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIClockSourceGet_IgnoreBool = (int)1;
}

void SSIClockSourceGet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIClockSourceGet_CALL_INSTANCE));
  CMOCK_SSIClockSourceGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIClockSourceGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIClockSourceGet_CallInstance = CMock_Guts_MemChain(Mock.SSIClockSourceGet_CallInstance, cmock_guts_index);
  Mock.SSIClockSourceGet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIClockSourceGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIClockSourceGet_CALL_INSTANCE));
  CMOCK_SSIClockSourceGet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIClockSourceGet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIClockSourceGet_CallInstance = CMock_Guts_MemChain(Mock.SSIClockSourceGet_CallInstance, cmock_guts_index);
  Mock.SSIClockSourceGet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIClockSourceGet(cmock_call_instance, ui32Base);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIAdvModeSet(uint32_t ui32Base, uint32_t ui32Mode)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIAdvModeSet_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIAdvModeSet);
  cmock_call_instance = (CMOCK_SSIAdvModeSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIAdvModeSet_CallInstance);
  Mock.SSIAdvModeSet_CallInstance = CMock_Guts_MemNext(Mock.SSIAdvModeSet_CallInstance);
  if (Mock.SSIAdvModeSet_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvModeSet,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvModeSet,CMockString_ui32Mode);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Mode, ui32Mode, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIAdvModeSet(CMOCK_SSIAdvModeSet_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Mode)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Mode = ui32Mode;
}

void SSIAdvModeSet_CMockIgnore(void)
{
  Mock.SSIAdvModeSet_IgnoreBool = (int)1;
}

void SSIAdvModeSet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvModeSet_CALL_INSTANCE));
  CMOCK_SSIAdvModeSet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvModeSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvModeSet_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvModeSet_CallInstance, cmock_guts_index);
  Mock.SSIAdvModeSet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIAdvModeSet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Mode)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvModeSet_CALL_INSTANCE));
  CMOCK_SSIAdvModeSet_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvModeSet_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvModeSet_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvModeSet_CallInstance, cmock_guts_index);
  Mock.SSIAdvModeSet_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIAdvModeSet(cmock_call_instance, ui32Base, ui32Mode);
  UNITY_CLR_DETAILS();
}

void SSIAdvDataPutFrameEnd(uint32_t ui32Base, uint32_t ui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIAdvDataPutFrameEnd);
  cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIAdvDataPutFrameEnd_CallInstance);
  Mock.SSIAdvDataPutFrameEnd_CallInstance = CMock_Guts_MemNext(Mock.SSIAdvDataPutFrameEnd_CallInstance);
  if (Mock.SSIAdvDataPutFrameEnd_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvDataPutFrameEnd,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvDataPutFrameEnd,CMockString_ui32Data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Data, ui32Data, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIAdvDataPutFrameEnd(CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Data = ui32Data;
}

void SSIAdvDataPutFrameEnd_CMockIgnore(void)
{
  Mock.SSIAdvDataPutFrameEnd_IgnoreBool = (int)1;
}

void SSIAdvDataPutFrameEnd_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE));
  CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvDataPutFrameEnd_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvDataPutFrameEnd_CallInstance, cmock_guts_index);
  Mock.SSIAdvDataPutFrameEnd_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIAdvDataPutFrameEnd_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE));
  CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEnd_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvDataPutFrameEnd_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvDataPutFrameEnd_CallInstance, cmock_guts_index);
  Mock.SSIAdvDataPutFrameEnd_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIAdvDataPutFrameEnd(cmock_call_instance, ui32Base, ui32Data);
  UNITY_CLR_DETAILS();
}

int32_t SSIAdvDataPutFrameEndNonBlocking(uint32_t ui32Base, uint32_t ui32Data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIAdvDataPutFrameEndNonBlocking);
  cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance);
  Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance = CMock_Guts_MemNext(Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance);
  if (Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.SSIAdvDataPutFrameEndNonBlocking_FinalReturn;
    Mock.SSIAdvDataPutFrameEndNonBlocking_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvDataPutFrameEndNonBlocking,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvDataPutFrameEndNonBlocking,CMockString_ui32Data);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Data, ui32Data, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_SSIAdvDataPutFrameEndNonBlocking(CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base, uint32_t ui32Data)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
  cmock_call_instance->Expected_ui32Data = ui32Data;
}

void SSIAdvDataPutFrameEndNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE));
  CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool = (int)1;
}

void SSIAdvDataPutFrameEndNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE));
  CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIAdvDataPutFrameEndNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data, int32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE));
  CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvDataPutFrameEndNonBlocking_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvDataPutFrameEndNonBlocking_CallInstance, cmock_guts_index);
  Mock.SSIAdvDataPutFrameEndNonBlocking_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIAdvDataPutFrameEndNonBlocking(cmock_call_instance, ui32Base, ui32Data);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void SSIAdvFrameHoldEnable(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIAdvFrameHoldEnable);
  cmock_call_instance = (CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIAdvFrameHoldEnable_CallInstance);
  Mock.SSIAdvFrameHoldEnable_CallInstance = CMock_Guts_MemNext(Mock.SSIAdvFrameHoldEnable_CallInstance);
  if (Mock.SSIAdvFrameHoldEnable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvFrameHoldEnable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIAdvFrameHoldEnable(CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIAdvFrameHoldEnable_CMockIgnore(void)
{
  Mock.SSIAdvFrameHoldEnable_IgnoreBool = (int)1;
}

void SSIAdvFrameHoldEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE));
  CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvFrameHoldEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvFrameHoldEnable_CallInstance, cmock_guts_index);
  Mock.SSIAdvFrameHoldEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIAdvFrameHoldEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE));
  CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvFrameHoldEnable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvFrameHoldEnable_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvFrameHoldEnable_CallInstance, cmock_guts_index);
  Mock.SSIAdvFrameHoldEnable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIAdvFrameHoldEnable(cmock_call_instance, ui32Base);
  UNITY_CLR_DETAILS();
}

void SSIAdvFrameHoldDisable(uint32_t ui32Base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSIAdvFrameHoldDisable);
  cmock_call_instance = (CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSIAdvFrameHoldDisable_CallInstance);
  Mock.SSIAdvFrameHoldDisable_CallInstance = CMock_Guts_MemNext(Mock.SSIAdvFrameHoldDisable_CallInstance);
  if (Mock.SSIAdvFrameHoldDisable_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->IgnoreMode != CMOCK_ARG_NONE)
  {
  {
    UNITY_SET_DETAILS(CMockString_SSIAdvFrameHoldDisable,CMockString_ui32Base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_ui32Base, ui32Base, cmock_line, CMockStringMismatch);
  }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_SSIAdvFrameHoldDisable(CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE* cmock_call_instance, uint32_t ui32Base)
{
  cmock_call_instance->Expected_ui32Base = ui32Base;
}

void SSIAdvFrameHoldDisable_CMockIgnore(void)
{
  Mock.SSIAdvFrameHoldDisable_IgnoreBool = (int)1;
}

void SSIAdvFrameHoldDisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE));
  CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvFrameHoldDisable_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvFrameHoldDisable_CallInstance, cmock_guts_index);
  Mock.SSIAdvFrameHoldDisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_NONE;
}

void SSIAdvFrameHoldDisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE));
  CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSIAdvFrameHoldDisable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSIAdvFrameHoldDisable_CallInstance = CMock_Guts_MemChain(Mock.SSIAdvFrameHoldDisable_CallInstance, cmock_guts_index);
  Mock.SSIAdvFrameHoldDisable_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->IgnoreMode = CMOCK_ARG_ALL;
  CMockExpectParameters_SSIAdvFrameHoldDisable(cmock_call_instance, ui32Base);
  UNITY_CLR_DETAILS();
}

