/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockdtc.h"

static const char* CMockString_cell = "cell";
static const char* CMockString_data = "data";
static const char* CMockString_dtc_get_update_hp = "dtc_get_update_hp";
static const char* CMockString_dtc_get_update_lp = "dtc_get_update_lp";
static const char* CMockString_dtc_send_16bit = "dtc_send_16bit";
static const char* CMockString_dtc_send_8bit = "dtc_send_8bit";
static const char* CMockString_dtc_send_cell = "dtc_send_cell";
static const char* CMockString_dtc_send_cell_16bit = "dtc_send_cell_16bit";
static const char* CMockString_dtc_send_cell_8bit = "dtc_send_cell_8bit";
static const char* CMockString_dtc_send_general = "dtc_send_general";
static const char* CMockString_dtc_set_update_hp = "dtc_set_update_hp";
static const char* CMockString_dtc_set_update_lp = "dtc_set_update_lp";
static const char* CMockString_dtc_update_tick_hp = "dtc_update_tick_hp";
static const char* CMockString_dtc_update_tick_lp = "dtc_update_tick_lp";
static const char* CMockString_fault_code = "fault_code";
static const char* CMockString_flag = "flag";
static const char* CMockString_state = "state";

typedef struct _CMOCK_dtc_send_general_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;

} CMOCK_dtc_send_general_CALL_INSTANCE;

typedef struct _CMOCK_dtc_send_8bit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;
  uint8_t Expected_data;

} CMOCK_dtc_send_8bit_CALL_INSTANCE;

typedef struct _CMOCK_dtc_send_16bit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;
  uint16_t Expected_data;

} CMOCK_dtc_send_16bit_CALL_INSTANCE;

typedef struct _CMOCK_dtc_send_cell_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;
  uint8_t Expected_cell;

} CMOCK_dtc_send_cell_CALL_INSTANCE;

typedef struct _CMOCK_dtc_send_cell_8bit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;
  uint8_t Expected_cell;
  uint8_t Expected_data;

} CMOCK_dtc_send_cell_8bit_CALL_INSTANCE;

typedef struct _CMOCK_dtc_send_cell_16bit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16_t Expected_fault_code;
  dtc_state_e Expected_state;
  uint8_t Expected_cell;
  uint16_t Expected_data;

} CMOCK_dtc_send_cell_16bit_CALL_INSTANCE;

typedef struct _CMOCK_dtc_update_tick_hp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_dtc_update_tick_hp_CALL_INSTANCE;

typedef struct _CMOCK_dtc_get_update_hp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_dtc_get_update_hp_CALL_INSTANCE;

typedef struct _CMOCK_dtc_set_update_hp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool Expected_flag;

} CMOCK_dtc_set_update_hp_CALL_INSTANCE;

typedef struct _CMOCK_dtc_update_tick_lp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_dtc_update_tick_lp_CALL_INSTANCE;

typedef struct _CMOCK_dtc_get_update_lp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_dtc_get_update_lp_CALL_INSTANCE;

typedef struct _CMOCK_dtc_set_update_lp_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool Expected_flag;

} CMOCK_dtc_set_update_lp_CALL_INSTANCE;

static struct MockdtcInstance
{
  int dtc_send_general_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_general_CallInstance;
  int dtc_send_8bit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_8bit_CallInstance;
  int dtc_send_16bit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_16bit_CallInstance;
  int dtc_send_cell_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_cell_CallInstance;
  int dtc_send_cell_8bit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_cell_8bit_CallInstance;
  int dtc_send_cell_16bit_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_send_cell_16bit_CallInstance;
  int dtc_update_tick_hp_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_update_tick_hp_CallInstance;
  int dtc_get_update_hp_IgnoreBool;
  bool dtc_get_update_hp_FinalReturn;
  CMOCK_MEM_INDEX_TYPE dtc_get_update_hp_CallInstance;
  int dtc_set_update_hp_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_set_update_hp_CallInstance;
  int dtc_update_tick_lp_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_update_tick_lp_CallInstance;
  int dtc_get_update_lp_IgnoreBool;
  bool dtc_get_update_lp_FinalReturn;
  CMOCK_MEM_INDEX_TYPE dtc_get_update_lp_CallInstance;
  int dtc_set_update_lp_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE dtc_set_update_lp_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockdtc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.dtc_send_general_IgnoreBool)
    Mock.dtc_send_general_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_general);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_general_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_send_8bit_IgnoreBool)
    Mock.dtc_send_8bit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_8bit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_8bit_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_send_16bit_IgnoreBool)
    Mock.dtc_send_16bit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_16bit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_16bit_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_send_cell_IgnoreBool)
    Mock.dtc_send_cell_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_cell_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_send_cell_8bit_IgnoreBool)
    Mock.dtc_send_cell_8bit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell_8bit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_cell_8bit_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_send_cell_16bit_IgnoreBool)
    Mock.dtc_send_cell_16bit_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell_16bit);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_send_cell_16bit_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_update_tick_hp_IgnoreBool)
    Mock.dtc_update_tick_hp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_update_tick_hp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_update_tick_hp_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_get_update_hp_IgnoreBool)
    Mock.dtc_get_update_hp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_get_update_hp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_get_update_hp_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_set_update_hp_IgnoreBool)
    Mock.dtc_set_update_hp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_set_update_hp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_set_update_hp_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_update_tick_lp_IgnoreBool)
    Mock.dtc_update_tick_lp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_update_tick_lp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_update_tick_lp_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_get_update_lp_IgnoreBool)
    Mock.dtc_get_update_lp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_get_update_lp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_get_update_lp_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.dtc_set_update_lp_IgnoreBool)
    Mock.dtc_set_update_lp_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_dtc_set_update_lp);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.dtc_set_update_lp_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockdtc_Init(void)
{
  Mockdtc_Destroy();
}

void Mockdtc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void dtc_send_general(uint16_t fault_code, dtc_state_e state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_general_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_general);
  cmock_call_instance = (CMOCK_dtc_send_general_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_general_CallInstance);
  Mock.dtc_send_general_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_general_CallInstance);
  if (Mock.dtc_send_general_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_general,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_general,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_general(CMOCK_dtc_send_general_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
}

void dtc_send_general_CMockIgnore(void)
{
  Mock.dtc_send_general_IgnoreBool = (int)1;
}

void dtc_send_general_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_general_CALL_INSTANCE));
  CMOCK_dtc_send_general_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_general_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_general_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_general_CallInstance, cmock_guts_index);
  Mock.dtc_send_general_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_general(cmock_call_instance, fault_code, state);
  UNITY_CLR_DETAILS();
}

void dtc_send_8bit(uint16_t fault_code, dtc_state_e state, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_8bit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_8bit);
  cmock_call_instance = (CMOCK_dtc_send_8bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_8bit_CallInstance);
  Mock.dtc_send_8bit_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_8bit_CallInstance);
  if (Mock.dtc_send_8bit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_8bit,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_8bit,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_8bit,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_8bit(CMOCK_dtc_send_8bit_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state, uint8_t data)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
  cmock_call_instance->Expected_data = data;
}

void dtc_send_8bit_CMockIgnore(void)
{
  Mock.dtc_send_8bit_IgnoreBool = (int)1;
}

void dtc_send_8bit_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_8bit_CALL_INSTANCE));
  CMOCK_dtc_send_8bit_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_8bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_8bit_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_8bit_CallInstance, cmock_guts_index);
  Mock.dtc_send_8bit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_8bit(cmock_call_instance, fault_code, state, data);
  UNITY_CLR_DETAILS();
}

void dtc_send_16bit(uint16_t fault_code, dtc_state_e state, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_16bit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_16bit);
  cmock_call_instance = (CMOCK_dtc_send_16bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_16bit_CallInstance);
  Mock.dtc_send_16bit_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_16bit_CallInstance);
  if (Mock.dtc_send_16bit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_16bit,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_16bit,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_16bit,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_16bit(CMOCK_dtc_send_16bit_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state, uint16_t data)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
  cmock_call_instance->Expected_data = data;
}

void dtc_send_16bit_CMockIgnore(void)
{
  Mock.dtc_send_16bit_IgnoreBool = (int)1;
}

void dtc_send_16bit_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_16bit_CALL_INSTANCE));
  CMOCK_dtc_send_16bit_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_16bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_16bit_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_16bit_CallInstance, cmock_guts_index);
  Mock.dtc_send_16bit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_16bit(cmock_call_instance, fault_code, state, data);
  UNITY_CLR_DETAILS();
}

void dtc_send_cell(uint16_t fault_code, dtc_state_e state, uint8_t cell)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_cell_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell);
  cmock_call_instance = (CMOCK_dtc_send_cell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_cell_CallInstance);
  Mock.dtc_send_cell_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_cell_CallInstance);
  if (Mock.dtc_send_cell_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell,CMockString_cell);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cell, cell, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_cell(CMOCK_dtc_send_cell_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state, uint8_t cell)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
  cmock_call_instance->Expected_cell = cell;
}

void dtc_send_cell_CMockIgnore(void)
{
  Mock.dtc_send_cell_IgnoreBool = (int)1;
}

void dtc_send_cell_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state, uint8_t cell)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_cell_CALL_INSTANCE));
  CMOCK_dtc_send_cell_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_cell_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_cell_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_cell_CallInstance, cmock_guts_index);
  Mock.dtc_send_cell_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_cell(cmock_call_instance, fault_code, state, cell);
  UNITY_CLR_DETAILS();
}

void dtc_send_cell_8bit(uint16_t fault_code, dtc_state_e state, uint8_t cell, uint8_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_cell_8bit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell_8bit);
  cmock_call_instance = (CMOCK_dtc_send_cell_8bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_cell_8bit_CallInstance);
  Mock.dtc_send_cell_8bit_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_cell_8bit_CallInstance);
  if (Mock.dtc_send_cell_8bit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_8bit,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_8bit,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_8bit,CMockString_cell);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cell, cell, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_8bit,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_cell_8bit(CMOCK_dtc_send_cell_8bit_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state, uint8_t cell, uint8_t data)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
  cmock_call_instance->Expected_cell = cell;
  cmock_call_instance->Expected_data = data;
}

void dtc_send_cell_8bit_CMockIgnore(void)
{
  Mock.dtc_send_cell_8bit_IgnoreBool = (int)1;
}

void dtc_send_cell_8bit_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state, uint8_t cell, uint8_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_cell_8bit_CALL_INSTANCE));
  CMOCK_dtc_send_cell_8bit_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_cell_8bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_cell_8bit_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_cell_8bit_CallInstance, cmock_guts_index);
  Mock.dtc_send_cell_8bit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_cell_8bit(cmock_call_instance, fault_code, state, cell, data);
  UNITY_CLR_DETAILS();
}

void dtc_send_cell_16bit(uint16_t fault_code, dtc_state_e state, uint8_t cell, uint16_t data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_send_cell_16bit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_send_cell_16bit);
  cmock_call_instance = (CMOCK_dtc_send_cell_16bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_send_cell_16bit_CallInstance);
  Mock.dtc_send_cell_16bit_CallInstance = CMock_Guts_MemNext(Mock.dtc_send_cell_16bit_CallInstance);
  if (Mock.dtc_send_cell_16bit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_16bit,CMockString_fault_code);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_fault_code, fault_code, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_16bit,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_state), (void*)(&state), sizeof(dtc_state_e), cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_16bit,CMockString_cell);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_cell, cell, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_dtc_send_cell_16bit,CMockString_data);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_data, data, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_send_cell_16bit(CMOCK_dtc_send_cell_16bit_CALL_INSTANCE* cmock_call_instance, uint16_t fault_code, dtc_state_e state, uint8_t cell, uint16_t data)
{
  cmock_call_instance->Expected_fault_code = fault_code;
  memcpy(&cmock_call_instance->Expected_state, &state, sizeof(dtc_state_e));
  cmock_call_instance->Expected_cell = cell;
  cmock_call_instance->Expected_data = data;
}

void dtc_send_cell_16bit_CMockIgnore(void)
{
  Mock.dtc_send_cell_16bit_IgnoreBool = (int)1;
}

void dtc_send_cell_16bit_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16_t fault_code, dtc_state_e state, uint8_t cell, uint16_t data)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_send_cell_16bit_CALL_INSTANCE));
  CMOCK_dtc_send_cell_16bit_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_send_cell_16bit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_send_cell_16bit_CallInstance = CMock_Guts_MemChain(Mock.dtc_send_cell_16bit_CallInstance, cmock_guts_index);
  Mock.dtc_send_cell_16bit_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_send_cell_16bit(cmock_call_instance, fault_code, state, cell, data);
  UNITY_CLR_DETAILS();
}

void dtc_update_tick_hp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_update_tick_hp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_update_tick_hp);
  cmock_call_instance = (CMOCK_dtc_update_tick_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_update_tick_hp_CallInstance);
  Mock.dtc_update_tick_hp_CallInstance = CMock_Guts_MemNext(Mock.dtc_update_tick_hp_CallInstance);
  if (Mock.dtc_update_tick_hp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void dtc_update_tick_hp_CMockIgnore(void)
{
  Mock.dtc_update_tick_hp_IgnoreBool = (int)1;
}

void dtc_update_tick_hp_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_update_tick_hp_CALL_INSTANCE));
  CMOCK_dtc_update_tick_hp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_update_tick_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_update_tick_hp_CallInstance = CMock_Guts_MemChain(Mock.dtc_update_tick_hp_CallInstance, cmock_guts_index);
  Mock.dtc_update_tick_hp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

bool dtc_get_update_hp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_get_update_hp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_get_update_hp);
  cmock_call_instance = (CMOCK_dtc_get_update_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_get_update_hp_CallInstance);
  Mock.dtc_get_update_hp_CallInstance = CMock_Guts_MemNext(Mock.dtc_get_update_hp_CallInstance);
  if (Mock.dtc_get_update_hp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dtc_get_update_hp_FinalReturn;
    Mock.dtc_get_update_hp_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dtc_get_update_hp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_get_update_hp_CALL_INSTANCE));
  CMOCK_dtc_get_update_hp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_get_update_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_get_update_hp_CallInstance = CMock_Guts_MemChain(Mock.dtc_get_update_hp_CallInstance, cmock_guts_index);
  Mock.dtc_get_update_hp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dtc_get_update_hp_IgnoreBool = (int)1;
}

void dtc_get_update_hp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_get_update_hp_CALL_INSTANCE));
  CMOCK_dtc_get_update_hp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_get_update_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_get_update_hp_CallInstance = CMock_Guts_MemChain(Mock.dtc_get_update_hp_CallInstance, cmock_guts_index);
  Mock.dtc_get_update_hp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void dtc_set_update_hp(bool flag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_set_update_hp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_set_update_hp);
  cmock_call_instance = (CMOCK_dtc_set_update_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_set_update_hp_CallInstance);
  Mock.dtc_set_update_hp_CallInstance = CMock_Guts_MemNext(Mock.dtc_set_update_hp_CallInstance);
  if (Mock.dtc_set_update_hp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_set_update_hp,CMockString_flag);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_flag, flag, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_set_update_hp(CMOCK_dtc_set_update_hp_CALL_INSTANCE* cmock_call_instance, bool flag)
{
  cmock_call_instance->Expected_flag = flag;
}

void dtc_set_update_hp_CMockIgnore(void)
{
  Mock.dtc_set_update_hp_IgnoreBool = (int)1;
}

void dtc_set_update_hp_CMockExpect(UNITY_LINE_TYPE cmock_line, bool flag)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_set_update_hp_CALL_INSTANCE));
  CMOCK_dtc_set_update_hp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_set_update_hp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_set_update_hp_CallInstance = CMock_Guts_MemChain(Mock.dtc_set_update_hp_CallInstance, cmock_guts_index);
  Mock.dtc_set_update_hp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_set_update_hp(cmock_call_instance, flag);
  UNITY_CLR_DETAILS();
}

void dtc_update_tick_lp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_update_tick_lp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_update_tick_lp);
  cmock_call_instance = (CMOCK_dtc_update_tick_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_update_tick_lp_CallInstance);
  Mock.dtc_update_tick_lp_CallInstance = CMock_Guts_MemNext(Mock.dtc_update_tick_lp_CallInstance);
  if (Mock.dtc_update_tick_lp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void dtc_update_tick_lp_CMockIgnore(void)
{
  Mock.dtc_update_tick_lp_IgnoreBool = (int)1;
}

void dtc_update_tick_lp_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_update_tick_lp_CALL_INSTANCE));
  CMOCK_dtc_update_tick_lp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_update_tick_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_update_tick_lp_CallInstance = CMock_Guts_MemChain(Mock.dtc_update_tick_lp_CallInstance, cmock_guts_index);
  Mock.dtc_update_tick_lp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

bool dtc_get_update_lp(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_get_update_lp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_get_update_lp);
  cmock_call_instance = (CMOCK_dtc_get_update_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_get_update_lp_CallInstance);
  Mock.dtc_get_update_lp_CallInstance = CMock_Guts_MemNext(Mock.dtc_get_update_lp_CallInstance);
  if (Mock.dtc_get_update_lp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.dtc_get_update_lp_FinalReturn;
    Mock.dtc_get_update_lp_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void dtc_get_update_lp_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_get_update_lp_CALL_INSTANCE));
  CMOCK_dtc_get_update_lp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_get_update_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_get_update_lp_CallInstance = CMock_Guts_MemChain(Mock.dtc_get_update_lp_CallInstance, cmock_guts_index);
  Mock.dtc_get_update_lp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.dtc_get_update_lp_IgnoreBool = (int)1;
}

void dtc_get_update_lp_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_get_update_lp_CALL_INSTANCE));
  CMOCK_dtc_get_update_lp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_get_update_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_get_update_lp_CallInstance = CMock_Guts_MemChain(Mock.dtc_get_update_lp_CallInstance, cmock_guts_index);
  Mock.dtc_get_update_lp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void dtc_set_update_lp(bool flag)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_dtc_set_update_lp_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_dtc_set_update_lp);
  cmock_call_instance = (CMOCK_dtc_set_update_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.dtc_set_update_lp_CallInstance);
  Mock.dtc_set_update_lp_CallInstance = CMock_Guts_MemNext(Mock.dtc_set_update_lp_CallInstance);
  if (Mock.dtc_set_update_lp_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_dtc_set_update_lp,CMockString_flag);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_flag, flag, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_dtc_set_update_lp(CMOCK_dtc_set_update_lp_CALL_INSTANCE* cmock_call_instance, bool flag)
{
  cmock_call_instance->Expected_flag = flag;
}

void dtc_set_update_lp_CMockIgnore(void)
{
  Mock.dtc_set_update_lp_IgnoreBool = (int)1;
}

void dtc_set_update_lp_CMockExpect(UNITY_LINE_TYPE cmock_line, bool flag)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_dtc_set_update_lp_CALL_INSTANCE));
  CMOCK_dtc_set_update_lp_CALL_INSTANCE* cmock_call_instance = (CMOCK_dtc_set_update_lp_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.dtc_set_update_lp_CallInstance = CMock_Guts_MemChain(Mock.dtc_set_update_lp_CallInstance, cmock_guts_index);
  Mock.dtc_set_update_lp_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_dtc_set_update_lp(cmock_call_instance, flag);
  UNITY_CLR_DETAILS();
}

