/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mocksdc_control.h"

static const char* CMockString_sdc_control_close = "sdc_control_close";
static const char* CMockString_sdc_control_init = "sdc_control_init";
static const char* CMockString_sdc_control_open = "sdc_control_open";

typedef struct _CMOCK_sdc_control_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_sdc_control_init_CALL_INSTANCE;

typedef struct _CMOCK_sdc_control_open_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_sdc_control_open_CALL_INSTANCE;

typedef struct _CMOCK_sdc_control_close_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_sdc_control_close_CALL_INSTANCE;

static struct Mocksdc_controlInstance
{
  CMOCK_MEM_INDEX_TYPE sdc_control_init_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdc_control_open_CallInstance;
  CMOCK_MEM_INDEX_TYPE sdc_control_close_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mocksdc_control_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_SET_DETAIL(CMockString_sdc_control_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdc_control_init_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_sdc_control_open);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdc_control_open_CallInstance, cmock_line, CMockStringCalledLess);
  UNITY_SET_DETAIL(CMockString_sdc_control_close);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.sdc_control_close_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mocksdc_control_Init(void)
{
  Mocksdc_control_Destroy();
}

void Mocksdc_control_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void sdc_control_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdc_control_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sdc_control_init);
  cmock_call_instance = (CMOCK_sdc_control_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdc_control_init_CallInstance);
  Mock.sdc_control_init_CallInstance = CMock_Guts_MemNext(Mock.sdc_control_init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void sdc_control_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdc_control_init_CALL_INSTANCE));
  CMOCK_sdc_control_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdc_control_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdc_control_init_CallInstance = CMock_Guts_MemChain(Mock.sdc_control_init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void sdc_control_open(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdc_control_open_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sdc_control_open);
  cmock_call_instance = (CMOCK_sdc_control_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdc_control_open_CallInstance);
  Mock.sdc_control_open_CallInstance = CMock_Guts_MemNext(Mock.sdc_control_open_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void sdc_control_open_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdc_control_open_CALL_INSTANCE));
  CMOCK_sdc_control_open_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdc_control_open_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdc_control_open_CallInstance = CMock_Guts_MemChain(Mock.sdc_control_open_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void sdc_control_close(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_sdc_control_close_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_sdc_control_close);
  cmock_call_instance = (CMOCK_sdc_control_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.sdc_control_close_CallInstance);
  Mock.sdc_control_close_CallInstance = CMock_Guts_MemNext(Mock.sdc_control_close_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void sdc_control_close_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_sdc_control_close_CALL_INSTANCE));
  CMOCK_sdc_control_close_CALL_INSTANCE* cmock_call_instance = (CMOCK_sdc_control_close_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.sdc_control_close_CallInstance = CMock_Guts_MemChain(Mock.sdc_control_close_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

