/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockspi.h"

static const char* CMockString_SSI0_init = "SSI0_init";
static const char* CMockString_SSI1_init = "SSI1_init";
static const char* CMockString_base = "base";
static const char* CMockString_data = "data";
static const char* CMockString_len = "len";
static const char* CMockString_rx_data = "rx_data";
static const char* CMockString_rx_len = "rx_len";
static const char* CMockString_spiTransfer = "spiTransfer";
static const char* CMockString_spi_write_array = "spi_write_array";
static const char* CMockString_spi_write_read = "spi_write_read";
static const char* CMockString_tx = "tx";
static const char* CMockString_tx_data = "tx_data";
static const char* CMockString_tx_len = "tx_len";

typedef struct _CMOCK_SSI0_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SSI0_init_CALL_INSTANCE;

typedef struct _CMOCK_SSI1_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_SSI1_init_CALL_INSTANCE;

typedef struct _CMOCK_spi_write_read_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t* Expected_tx_data;
  uint8_t Expected_tx_len;
  uint8_t* Expected_rx_data;
  uint8_t Expected_rx_len;
  uint32_t Expected_base;

} CMOCK_spi_write_read_CALL_INSTANCE;

typedef struct _CMOCK_spi_write_array_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint8_t Expected_len;
  uint8_t* Expected_data;
  uint32_t Expected_base;

} CMOCK_spi_write_array_CALL_INSTANCE;

typedef struct _CMOCK_spiTransfer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32_t ReturnVal;
  uint8_t Expected_tx;
  uint32_t Expected_base;

} CMOCK_spiTransfer_CALL_INSTANCE;

static struct MockspiInstance
{
  int SSI0_init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSI0_init_CallInstance;
  int SSI1_init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE SSI1_init_CallInstance;
  int spi_write_read_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE spi_write_read_CallInstance;
  int spi_write_array_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE spi_write_array_CallInstance;
  int spiTransfer_IgnoreBool;
  uint32_t spiTransfer_FinalReturn;
  CMOCK_MEM_INDEX_TYPE spiTransfer_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockspi_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.SSI0_init_IgnoreBool)
    Mock.SSI0_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSI0_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSI0_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.SSI1_init_IgnoreBool)
    Mock.SSI1_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_SSI1_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.SSI1_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.spi_write_read_IgnoreBool)
    Mock.spi_write_read_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_spi_write_read);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.spi_write_read_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.spi_write_array_IgnoreBool)
    Mock.spi_write_array_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_spi_write_array);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.spi_write_array_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.spiTransfer_IgnoreBool)
    Mock.spiTransfer_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_spiTransfer);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.spiTransfer_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockspi_Init(void)
{
  Mockspi_Destroy();
}

void Mockspi_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void SSI0_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSI0_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSI0_init);
  cmock_call_instance = (CMOCK_SSI0_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSI0_init_CallInstance);
  Mock.SSI0_init_CallInstance = CMock_Guts_MemNext(Mock.SSI0_init_CallInstance);
  if (Mock.SSI0_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SSI0_init_CMockIgnore(void)
{
  Mock.SSI0_init_IgnoreBool = (int)1;
}

void SSI0_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSI0_init_CALL_INSTANCE));
  CMOCK_SSI0_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSI0_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSI0_init_CallInstance = CMock_Guts_MemChain(Mock.SSI0_init_CallInstance, cmock_guts_index);
  Mock.SSI0_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void SSI1_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_SSI1_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_SSI1_init);
  cmock_call_instance = (CMOCK_SSI1_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.SSI1_init_CallInstance);
  Mock.SSI1_init_CallInstance = CMock_Guts_MemNext(Mock.SSI1_init_CallInstance);
  if (Mock.SSI1_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void SSI1_init_CMockIgnore(void)
{
  Mock.SSI1_init_IgnoreBool = (int)1;
}

void SSI1_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_SSI1_init_CALL_INSTANCE));
  CMOCK_SSI1_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_SSI1_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.SSI1_init_CallInstance = CMock_Guts_MemChain(Mock.SSI1_init_CallInstance, cmock_guts_index);
  Mock.SSI1_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void spi_write_read(uint8_t* tx_data, uint8_t tx_len, uint8_t* rx_data, uint8_t rx_len, uint32_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_write_read_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_write_read);
  cmock_call_instance = (CMOCK_spi_write_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_write_read_CallInstance);
  Mock.spi_write_read_CallInstance = CMock_Guts_MemNext(Mock.spi_write_read_CallInstance);
  if (Mock.spi_write_read_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_write_read,CMockString_tx_data);
    if (cmock_call_instance->Expected_tx_data == NULL)
      { UNITY_TEST_ASSERT_NULL(tx_data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_tx_data, tx_data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_read,CMockString_tx_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_tx_len, tx_len, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_read,CMockString_rx_data);
    if (cmock_call_instance->Expected_rx_data == NULL)
      { UNITY_TEST_ASSERT_NULL(rx_data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_rx_data, rx_data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_read,CMockString_rx_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_rx_len, rx_len, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_read,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_base, base, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_spi_write_read(CMOCK_spi_write_read_CALL_INSTANCE* cmock_call_instance, uint8_t* tx_data, uint8_t tx_len, uint8_t* rx_data, uint8_t rx_len, uint32_t base)
{
  cmock_call_instance->Expected_tx_data = tx_data;
  cmock_call_instance->Expected_tx_len = tx_len;
  cmock_call_instance->Expected_rx_data = rx_data;
  cmock_call_instance->Expected_rx_len = rx_len;
  cmock_call_instance->Expected_base = base;
}

void spi_write_read_CMockIgnore(void)
{
  Mock.spi_write_read_IgnoreBool = (int)1;
}

void spi_write_read_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t* tx_data, uint8_t tx_len, uint8_t* rx_data, uint8_t rx_len, uint32_t base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_write_read_CALL_INSTANCE));
  CMOCK_spi_write_read_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_write_read_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_write_read_CallInstance = CMock_Guts_MemChain(Mock.spi_write_read_CallInstance, cmock_guts_index);
  Mock.spi_write_read_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_write_read(cmock_call_instance, tx_data, tx_len, rx_data, rx_len, base);
  UNITY_CLR_DETAILS();
}

void spi_write_array(uint8_t len, uint8_t* data, uint32_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spi_write_array_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spi_write_array);
  cmock_call_instance = (CMOCK_spi_write_array_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spi_write_array_CallInstance);
  Mock.spi_write_array_CallInstance = CMock_Guts_MemNext(Mock.spi_write_array_CallInstance);
  if (Mock.spi_write_array_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spi_write_array,CMockString_len);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_len, len, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_array,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_data, data, 1, cmock_line, CMockStringMismatch); }
  }
  {
    UNITY_SET_DETAILS(CMockString_spi_write_array,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_base, base, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_spi_write_array(CMOCK_spi_write_array_CALL_INSTANCE* cmock_call_instance, uint8_t len, uint8_t* data, uint32_t base)
{
  cmock_call_instance->Expected_len = len;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_base = base;
}

void spi_write_array_CMockIgnore(void)
{
  Mock.spi_write_array_IgnoreBool = (int)1;
}

void spi_write_array_CMockExpect(UNITY_LINE_TYPE cmock_line, uint8_t len, uint8_t* data, uint32_t base)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spi_write_array_CALL_INSTANCE));
  CMOCK_spi_write_array_CALL_INSTANCE* cmock_call_instance = (CMOCK_spi_write_array_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spi_write_array_CallInstance = CMock_Guts_MemChain(Mock.spi_write_array_CallInstance, cmock_guts_index);
  Mock.spi_write_array_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spi_write_array(cmock_call_instance, len, data, base);
  UNITY_CLR_DETAILS();
}

uint32_t spiTransfer(uint8_t tx, uint32_t base)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_spiTransfer_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_spiTransfer);
  cmock_call_instance = (CMOCK_spiTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.spiTransfer_CallInstance);
  Mock.spiTransfer_CallInstance = CMock_Guts_MemNext(Mock.spiTransfer_CallInstance);
  if (Mock.spiTransfer_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.spiTransfer_FinalReturn;
    Mock.spiTransfer_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_SET_DETAILS(CMockString_spiTransfer,CMockString_tx);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_tx, tx, cmock_line, CMockStringMismatch);
  }
  {
    UNITY_SET_DETAILS(CMockString_spiTransfer,CMockString_base);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_base, base, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_spiTransfer(CMOCK_spiTransfer_CALL_INSTANCE* cmock_call_instance, uint8_t tx, uint32_t base)
{
  cmock_call_instance->Expected_tx = tx;
  cmock_call_instance->Expected_base = base;
}

void spiTransfer_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spiTransfer_CALL_INSTANCE));
  CMOCK_spiTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_spiTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spiTransfer_CallInstance = CMock_Guts_MemChain(Mock.spiTransfer_CallInstance, cmock_guts_index);
  Mock.spiTransfer_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.spiTransfer_IgnoreBool = (int)1;
}

void spiTransfer_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t tx, uint32_t base, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_spiTransfer_CALL_INSTANCE));
  CMOCK_spiTransfer_CALL_INSTANCE* cmock_call_instance = (CMOCK_spiTransfer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.spiTransfer_CallInstance = CMock_Guts_MemChain(Mock.spiTransfer_CallInstance, cmock_guts_index);
  Mock.spiTransfer_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_spiTransfer(cmock_call_instance, tx, base);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

