/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSSI_H
#define _MOCKSSI_H

#include <stdbool.h>
#include "driverlib/ssi.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockssi_Init(void);
void Mockssi_Destroy(void);
void Mockssi_Verify(void);


typedef void(*cmock_ssi_func_ptr1)(void);


#define SSIConfigSetExpClk_Ignore() SSIConfigSetExpClk_CMockIgnore()
void SSIConfigSetExpClk_CMockIgnore(void);
#define SSIConfigSetExpClk_ExpectAnyArgs() SSIConfigSetExpClk_CMockExpectAnyArgs(__LINE__)
void SSIConfigSetExpClk_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIConfigSetExpClk_Expect(ui32Base, ui32SSIClk, ui32Protocol, ui32Mode, ui32BitRate, ui32DataWidth) SSIConfigSetExpClk_CMockExpect(__LINE__, ui32Base, ui32SSIClk, ui32Protocol, ui32Mode, ui32BitRate, ui32DataWidth)
void SSIConfigSetExpClk_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32SSIClk, uint32_t ui32Protocol, uint32_t ui32Mode, uint32_t ui32BitRate, uint32_t ui32DataWidth);
#define SSIDataGet_Ignore() SSIDataGet_CMockIgnore()
void SSIDataGet_CMockIgnore(void);
#define SSIDataGet_ExpectAnyArgs() SSIDataGet_CMockExpectAnyArgs(__LINE__)
void SSIDataGet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIDataGet_Expect(ui32Base, pui32Data) SSIDataGet_CMockExpect(__LINE__, ui32Base, pui32Data)
void SSIDataGet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t* pui32Data);
#define SSIDataGet_ReturnThruPtr_pui32Data(pui32Data) SSIDataGet_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, sizeof(*pui32Data))
#define SSIDataGet_ReturnArrayThruPtr_pui32Data(pui32Data, cmock_len) SSIDataGet_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, (int)(cmock_len * (int)sizeof(*pui32Data)))
#define SSIDataGet_ReturnMemThruPtr_pui32Data(pui32Data, cmock_size) SSIDataGet_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, cmock_size)
void SSIDataGet_CMockReturnMemThruPtr_pui32Data(UNITY_LINE_TYPE cmock_line, uint32_t* pui32Data, int cmock_size);
#define SSIDataGetNonBlocking_IgnoreAndReturn(cmock_retval) SSIDataGetNonBlocking_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIDataGetNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIDataGetNonBlocking_ExpectAnyArgsAndReturn(cmock_retval) SSIDataGetNonBlocking_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIDataGetNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIDataGetNonBlocking_ExpectAndReturn(ui32Base, pui32Data, cmock_retval) SSIDataGetNonBlocking_CMockExpectAndReturn(__LINE__, ui32Base, pui32Data, cmock_retval)
void SSIDataGetNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t* pui32Data, int32_t cmock_to_return);
#define SSIDataGetNonBlocking_ReturnThruPtr_pui32Data(pui32Data) SSIDataGetNonBlocking_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, sizeof(*pui32Data))
#define SSIDataGetNonBlocking_ReturnArrayThruPtr_pui32Data(pui32Data, cmock_len) SSIDataGetNonBlocking_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, (int)(cmock_len * (int)sizeof(*pui32Data)))
#define SSIDataGetNonBlocking_ReturnMemThruPtr_pui32Data(pui32Data, cmock_size) SSIDataGetNonBlocking_CMockReturnMemThruPtr_pui32Data(__LINE__, pui32Data, cmock_size)
void SSIDataGetNonBlocking_CMockReturnMemThruPtr_pui32Data(UNITY_LINE_TYPE cmock_line, uint32_t* pui32Data, int cmock_size);
#define SSIDataPut_Ignore() SSIDataPut_CMockIgnore()
void SSIDataPut_CMockIgnore(void);
#define SSIDataPut_ExpectAnyArgs() SSIDataPut_CMockExpectAnyArgs(__LINE__)
void SSIDataPut_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIDataPut_Expect(ui32Base, ui32Data) SSIDataPut_CMockExpect(__LINE__, ui32Base, ui32Data)
void SSIDataPut_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data);
#define SSIDataPutNonBlocking_IgnoreAndReturn(cmock_retval) SSIDataPutNonBlocking_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIDataPutNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIDataPutNonBlocking_ExpectAnyArgsAndReturn(cmock_retval) SSIDataPutNonBlocking_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIDataPutNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIDataPutNonBlocking_ExpectAndReturn(ui32Base, ui32Data, cmock_retval) SSIDataPutNonBlocking_CMockExpectAndReturn(__LINE__, ui32Base, ui32Data, cmock_retval)
void SSIDataPutNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data, int32_t cmock_to_return);
#define SSIDisable_Ignore() SSIDisable_CMockIgnore()
void SSIDisable_CMockIgnore(void);
#define SSIDisable_ExpectAnyArgs() SSIDisable_CMockExpectAnyArgs(__LINE__)
void SSIDisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIDisable_Expect(ui32Base) SSIDisable_CMockExpect(__LINE__, ui32Base)
void SSIDisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base);
#define SSIEnable_Ignore() SSIEnable_CMockIgnore()
void SSIEnable_CMockIgnore(void);
#define SSIEnable_ExpectAnyArgs() SSIEnable_CMockExpectAnyArgs(__LINE__)
void SSIEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIEnable_Expect(ui32Base) SSIEnable_CMockExpect(__LINE__, ui32Base)
void SSIEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base);
#define SSIIntClear_Ignore() SSIIntClear_CMockIgnore()
void SSIIntClear_CMockIgnore(void);
#define SSIIntClear_ExpectAnyArgs() SSIIntClear_CMockExpectAnyArgs(__LINE__)
void SSIIntClear_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIIntClear_Expect(ui32Base, ui32IntFlags) SSIIntClear_CMockExpect(__LINE__, ui32Base, ui32IntFlags)
void SSIIntClear_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32IntFlags);
#define SSIIntEnable_Ignore() SSIIntEnable_CMockIgnore()
void SSIIntEnable_CMockIgnore(void);
#define SSIIntEnable_ExpectAnyArgs() SSIIntEnable_CMockExpectAnyArgs(__LINE__)
void SSIIntEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIIntEnable_Expect(ui32Base, ui32IntFlags) SSIIntEnable_CMockExpect(__LINE__, ui32Base, ui32IntFlags)
void SSIIntEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32IntFlags);
#define SSIIntRegister_Ignore() SSIIntRegister_CMockIgnore()
void SSIIntRegister_CMockIgnore(void);
#define SSIIntRegister_ExpectAnyArgs() SSIIntRegister_CMockExpectAnyArgs(__LINE__)
void SSIIntRegister_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIIntRegister_Expect(ui32Base, pfnHandler) SSIIntRegister_CMockExpect(__LINE__, ui32Base, pfnHandler)
void SSIIntRegister_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, cmock_ssi_func_ptr1 pfnHandler);
#define SSIIntStatus_IgnoreAndReturn(cmock_retval) SSIIntStatus_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIIntStatus_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define SSIIntStatus_ExpectAnyArgsAndReturn(cmock_retval) SSIIntStatus_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIIntStatus_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define SSIIntStatus_ExpectAndReturn(ui32Base, bMasked, cmock_retval) SSIIntStatus_CMockExpectAndReturn(__LINE__, ui32Base, bMasked, cmock_retval)
void SSIIntStatus_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, bool bMasked, uint32_t cmock_to_return);
#define SSIIntUnregister_Ignore() SSIIntUnregister_CMockIgnore()
void SSIIntUnregister_CMockIgnore(void);
#define SSIIntUnregister_ExpectAnyArgs() SSIIntUnregister_CMockExpectAnyArgs(__LINE__)
void SSIIntUnregister_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIIntUnregister_Expect(ui32Base) SSIIntUnregister_CMockExpect(__LINE__, ui32Base)
void SSIIntUnregister_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base);
#define SSIDMAEnable_Ignore() SSIDMAEnable_CMockIgnore()
void SSIDMAEnable_CMockIgnore(void);
#define SSIDMAEnable_ExpectAnyArgs() SSIDMAEnable_CMockExpectAnyArgs(__LINE__)
void SSIDMAEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIDMAEnable_Expect(ui32Base, ui32DMAFlags) SSIDMAEnable_CMockExpect(__LINE__, ui32Base, ui32DMAFlags)
void SSIDMAEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32DMAFlags);
#define SSIDMADisable_Ignore() SSIDMADisable_CMockIgnore()
void SSIDMADisable_CMockIgnore(void);
#define SSIDMADisable_ExpectAnyArgs() SSIDMADisable_CMockExpectAnyArgs(__LINE__)
void SSIDMADisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIDMADisable_Expect(ui32Base, ui32DMAFlags) SSIDMADisable_CMockExpect(__LINE__, ui32Base, ui32DMAFlags)
void SSIDMADisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32DMAFlags);
#define SSIBusy_IgnoreAndReturn(cmock_retval) SSIBusy_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIBusy_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define SSIBusy_ExpectAnyArgsAndReturn(cmock_retval) SSIBusy_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIBusy_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define SSIBusy_ExpectAndReturn(ui32Base, cmock_retval) SSIBusy_CMockExpectAndReturn(__LINE__, ui32Base, cmock_retval)
void SSIBusy_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, bool cmock_to_return);
#define SSIClockSourceSet_Ignore() SSIClockSourceSet_CMockIgnore()
void SSIClockSourceSet_CMockIgnore(void);
#define SSIClockSourceSet_ExpectAnyArgs() SSIClockSourceSet_CMockExpectAnyArgs(__LINE__)
void SSIClockSourceSet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIClockSourceSet_Expect(ui32Base, ui32Source) SSIClockSourceSet_CMockExpect(__LINE__, ui32Base, ui32Source)
void SSIClockSourceSet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Source);
#define SSIClockSourceGet_IgnoreAndReturn(cmock_retval) SSIClockSourceGet_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIClockSourceGet_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define SSIClockSourceGet_ExpectAnyArgsAndReturn(cmock_retval) SSIClockSourceGet_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIClockSourceGet_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return);
#define SSIClockSourceGet_ExpectAndReturn(ui32Base, cmock_retval) SSIClockSourceGet_CMockExpectAndReturn(__LINE__, ui32Base, cmock_retval)
void SSIClockSourceGet_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t cmock_to_return);
#define SSIAdvModeSet_Ignore() SSIAdvModeSet_CMockIgnore()
void SSIAdvModeSet_CMockIgnore(void);
#define SSIAdvModeSet_ExpectAnyArgs() SSIAdvModeSet_CMockExpectAnyArgs(__LINE__)
void SSIAdvModeSet_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIAdvModeSet_Expect(ui32Base, ui32Mode) SSIAdvModeSet_CMockExpect(__LINE__, ui32Base, ui32Mode)
void SSIAdvModeSet_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Mode);
#define SSIAdvDataPutFrameEnd_Ignore() SSIAdvDataPutFrameEnd_CMockIgnore()
void SSIAdvDataPutFrameEnd_CMockIgnore(void);
#define SSIAdvDataPutFrameEnd_ExpectAnyArgs() SSIAdvDataPutFrameEnd_CMockExpectAnyArgs(__LINE__)
void SSIAdvDataPutFrameEnd_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIAdvDataPutFrameEnd_Expect(ui32Base, ui32Data) SSIAdvDataPutFrameEnd_CMockExpect(__LINE__, ui32Base, ui32Data)
void SSIAdvDataPutFrameEnd_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data);
#define SSIAdvDataPutFrameEndNonBlocking_IgnoreAndReturn(cmock_retval) SSIAdvDataPutFrameEndNonBlocking_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void SSIAdvDataPutFrameEndNonBlocking_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIAdvDataPutFrameEndNonBlocking_ExpectAnyArgsAndReturn(cmock_retval) SSIAdvDataPutFrameEndNonBlocking_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void SSIAdvDataPutFrameEndNonBlocking_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int32_t cmock_to_return);
#define SSIAdvDataPutFrameEndNonBlocking_ExpectAndReturn(ui32Base, ui32Data, cmock_retval) SSIAdvDataPutFrameEndNonBlocking_CMockExpectAndReturn(__LINE__, ui32Base, ui32Data, cmock_retval)
void SSIAdvDataPutFrameEndNonBlocking_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base, uint32_t ui32Data, int32_t cmock_to_return);
#define SSIAdvFrameHoldEnable_Ignore() SSIAdvFrameHoldEnable_CMockIgnore()
void SSIAdvFrameHoldEnable_CMockIgnore(void);
#define SSIAdvFrameHoldEnable_ExpectAnyArgs() SSIAdvFrameHoldEnable_CMockExpectAnyArgs(__LINE__)
void SSIAdvFrameHoldEnable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIAdvFrameHoldEnable_Expect(ui32Base) SSIAdvFrameHoldEnable_CMockExpect(__LINE__, ui32Base)
void SSIAdvFrameHoldEnable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base);
#define SSIAdvFrameHoldDisable_Ignore() SSIAdvFrameHoldDisable_CMockIgnore()
void SSIAdvFrameHoldDisable_CMockIgnore(void);
#define SSIAdvFrameHoldDisable_ExpectAnyArgs() SSIAdvFrameHoldDisable_CMockExpectAnyArgs(__LINE__)
void SSIAdvFrameHoldDisable_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line);
#define SSIAdvFrameHoldDisable_Expect(ui32Base) SSIAdvFrameHoldDisable_CMockExpect(__LINE__, ui32Base)
void SSIAdvFrameHoldDisable_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32_t ui32Base);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
