/**
 * This file was autogenerated using the WR dbc_to_c.py
 */

#include <stdbool.h>
#include <stdint.h>

void set_582_BMS_f027_VehicleIdle(uint8_t data[], bool value);
void set_582_BMS_w017_DischargeCompleted(uint8_t data[], bool value);
void set_582_BMS_a010_CellTemperatureOORL(uint8_t data[], bool value);
void set_582_BMS_w002_CellUndervoltage(uint8_t data[], bool value);
void set_582_BMS_w016_ChargeCompleted(uint8_t data[], bool value);
void set_582_BMS_FaultMatrixMux(uint8_t data[], uint8_t value);
void set_582_BMS_w011_ChargerMIA(uint8_t data[], bool value);
void set_582_BMS_w026_SelfTestError(uint8_t data[], bool value);
void set_582_BMS_c029_VoltageFailsafeMode(uint8_t data[], bool value);
void set_582_BMS_w014_DischargeCurrentLimitOver(uint8_t data[], bool value);
void set_582_BMS_w033_ChargingTimeout(uint8_t data[], bool value);
void set_582_BMS_w015_ChargerFault(uint8_t data[], bool value);
void set_582_BMS_w007_CellTemperatureAbove60degC(uint8_t data[], bool value);
void set_582_BMS_c004_CellVoltageOORL(uint8_t data[], bool value);
void set_582_BMS_f012_ChargerConnected(uint8_t data[], bool value);
void set_582_BMS_a009_CellTemperatureOORH(uint8_t data[], bool value);
void set_582_BMS_f032_ChargerEnabled(uint8_t data[], bool value);
void set_582_BMS_c003_CellVoltageOORH(uint8_t data[], bool value);
void set_582_BMS_a024_CellHighImpedance(uint8_t data[], bool value);
void set_582_BMS_w005_CellOvertemperature(uint8_t data[], bool value);
void set_582_BMS_c018_CurrentSensorOORH(uint8_t data[], bool value);
void set_582_BMS_a022_AuxMIA(uint8_t data[], bool value);
void set_582_BMS_a020_PowerStageOpen(uint8_t data[], bool value);
void set_582_BMS_w028_InverterSDCOpenRequest(uint8_t data[], bool value);
void set_582_BMS_a031_StartupFailure(uint8_t data[], bool value);
void set_582_BMS_w001_CellOvervoltage(uint8_t data[], bool value);
void set_582_BMS_c030_CurrentFailsafeMode(uint8_t data[], bool value);
void set_582_BMS_w013_ChargeCurrentLimitOver(uint8_t data[], bool value);
void set_582_BMS_w023_PowerStageFailure(uint8_t data[], bool value);
void set_582_BMS_f021_BalancingActive(uint8_t data[], bool value);
void set_582_BMS_w006_CellUndertemperature(uint8_t data[], bool value);
void set_582_BMS_w008_CellTemperatureLostSensors(uint8_t data[], bool value);
void set_582_BMS_w025_isoSPIPECError(uint8_t data[], bool value);
void set_582_BMS_c019_CurrentSensorOORL(uint8_t data[], bool value);

void set_325_BMS_a024_Resistance(uint8_t data[], uint16_t value);
void set_325_BMS_w013_PackI(uint8_t data[], float value);
void set_325_BMS_w005_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_c003_CellVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_c018_SensorVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_w006_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_w007_CellTemperature(uint8_t data[], int8_t value);
void set_325_BMS_c003_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_c019_SensorVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_a010_SensorVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_c004_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_w014_PackI(uint8_t data[], float value);
void set_325_BMS_w028_InverterID(uint8_t data[], uint8_t value);
void set_325_BMS_w008_LostSensors(uint8_t data[], uint8_t value);
void set_325_BMS_w014_DischargeCurrentLimit(uint8_t data[], uint16_t value);
void set_325_BMS_w002_CellVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_w013_ChargeCurrentLimit(uint8_t data[], uint16_t value);
void set_325_BMS_w001_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_a009_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_w007_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_a009_SensorVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_w002_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_a024_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_w001_CellVoltage(uint8_t data[], uint16_t value);
void set_325_BMS_FaultCode(uint8_t data[], uint16_t value);
void set_325_BMS_w005_CellTemperature(uint8_t data[], int8_t value);
void set_325_BMS_a010_CellID(uint8_t data[], uint8_t value);
void set_325_BMS_w006_CellTemperature(uint8_t data[], int8_t value);
void set_325_BMS_c004_CellVoltage(uint8_t data[], uint16_t value);

