/**
 * This file was autogenerated using the WR fault_json_to_c.py
 */

#include <stdbool.h>
#include <stdint.h>

#define FAULT_ACTIVE 0x1

#define FAULT_FLAG 0x0
#define FAULT_ALERT 0x1
#define FAULT_CAUTION 0x2
#define FAULT_WARNING 0x3

#define W001_CELLOVERVOLTAGE 1
#define W002_CELLUNDERVOLTAGE 2
#define C003_CELLVOLTAGEOORH 3
#define C004_CELLVOLTAGEOORL 4
#define W005_CELLOVERTEMPERATURE 5
#define W006_CELLUNDERTEMPERATURE 6
#define W007_CELLTEMPERATUREABOVE60DEGC 7
#define W008_CELLTEMPERATURELOSTSENSORS 8
#define A009_CELLTEMPERATUREOORH 9
#define A010_CELLTEMPERATUREOORL 10
#define W011_CHARGERMIA 11
#define F012_CHARGERCONNECTED 12
#define W013_CHARGECURRENTLIMITOVER 13
#define W014_DISCHARGECURRENTLIMITOVER 14
#define W015_CHARGERFAULT 15
#define W016_CHARGECOMPLETED 16
#define W017_DISCHARGECOMPLETED 17
#define C018_CURRENTSENSOROORH 18
#define C019_CURRENTSENSOROORL 19
#define A020_POWERSTAGEOPEN 20
#define F021_BALANCINGACTIVE 21
#define A022_AUXMIA 22
#define W023_POWERSTAGEFAILURE 23
#define A024_CELLHIGHIMPEDANCE 24
#define W025_ISOSPIPECERROR 25
#define W026_SELFTESTERROR 26
#define F027_VEHICLEIDLE 27
#define W028_INVERTERSDCOPENREQUEST 28
#define C029_VOLTAGEFAILSAFEMODE 29
#define C030_CURRENTFAILSAFEMODE 30
#define A031_STARTUPFAILURE 31
#define F032_CHARGERENABLED 32
#define W033_CHARGINGTIMEOUT 33

bool is_fault_active(uint32_t faultID);

bool fault_set_wCellOvervoltage(uint8_t CellID, uint16_t CellVoltage);
bool fault_is_wCellOvervoltage(void);
void fault_clear_wCellOvervoltage(void);

bool fault_set_wCellUndervoltage(uint8_t CellID, uint16_t CellVoltage);
bool fault_is_wCellUndervoltage(void);
void fault_clear_wCellUndervoltage(void);

bool fault_set_cCellVoltageOORH(uint8_t CellID, uint16_t CellVoltage);
bool fault_is_cCellVoltageOORH(void);
void fault_clear_cCellVoltageOORH(void);

bool fault_set_cCellVoltageOORL(uint8_t CellID, uint16_t CellVoltage);
bool fault_is_cCellVoltageOORL(void);
void fault_clear_cCellVoltageOORL(void);

bool fault_set_wCellOvertemperature(uint8_t CellID, int8_t CellTemperature);
bool fault_is_wCellOvertemperature(void);
void fault_clear_wCellOvertemperature(void);

bool fault_set_wCellUndertemperature(uint8_t CellID, int8_t CellTemperature);
bool fault_is_wCellUndertemperature(void);
void fault_clear_wCellUndertemperature(void);

bool fault_set_wCellTemperatureAbove60degC(uint8_t CellID, int8_t CellTemperature);
bool fault_is_wCellTemperatureAbove60degC(void);
void fault_clear_wCellTemperatureAbove60degC(void);

bool fault_set_wCellTemperatureLostSensors(uint8_t LostSensors);
bool fault_is_wCellTemperatureLostSensors(void);
void fault_clear_wCellTemperatureLostSensors(void);

bool fault_set_aCellTemperatureOORH(uint8_t CellID, uint16_t SensorVoltage);
bool fault_is_aCellTemperatureOORH(void);
void fault_clear_aCellTemperatureOORH(void);

bool fault_set_aCellTemperatureOORL(uint8_t CellID, uint16_t SensorVoltage);
bool fault_is_aCellTemperatureOORL(void);
void fault_clear_aCellTemperatureOORL(void);

bool fault_set_wChargerMIA(void);
bool fault_is_wChargerMIA(void);
void fault_clear_wChargerMIA(void);

bool fault_set_fChargerConnected(void);
bool fault_is_fChargerConnected(void);
void fault_clear_fChargerConnected(void);

bool fault_set_wChargeCurrentLimitOver(uint16_t ChargeCurrentLimit, float PackI);
bool fault_is_wChargeCurrentLimitOver(void);
void fault_clear_wChargeCurrentLimitOver(void);

bool fault_set_wDischargeCurrentLimitOver(uint16_t DischargeCurrentLimit, float PackI);
bool fault_is_wDischargeCurrentLimitOver(void);
void fault_clear_wDischargeCurrentLimitOver(void);

bool fault_set_wChargerFault(void);
bool fault_is_wChargerFault(void);
void fault_clear_wChargerFault(void);

bool fault_set_wChargeCompleted(void);
bool fault_is_wChargeCompleted(void);
void fault_clear_wChargeCompleted(void);

bool fault_set_wDischargeCompleted(void);
bool fault_is_wDischargeCompleted(void);
void fault_clear_wDischargeCompleted(void);

bool fault_set_cCurrentSensorOORH(uint16_t SensorVoltage);
bool fault_is_cCurrentSensorOORH(void);
void fault_clear_cCurrentSensorOORH(void);

bool fault_set_cCurrentSensorOORL(uint16_t SensorVoltage);
bool fault_is_cCurrentSensorOORL(void);
void fault_clear_cCurrentSensorOORL(void);

bool fault_set_aPowerStageOpen(void);
bool fault_is_aPowerStageOpen(void);
void fault_clear_aPowerStageOpen(void);

bool fault_set_fBalancingActive(void);
bool fault_is_fBalancingActive(void);
void fault_clear_fBalancingActive(void);

bool fault_set_aAuxMIA(void);
bool fault_is_aAuxMIA(void);
void fault_clear_aAuxMIA(void);

bool fault_set_wPowerStageFailure(void);
bool fault_is_wPowerStageFailure(void);
void fault_clear_wPowerStageFailure(void);

bool fault_set_aCellHighImpedance(uint8_t CellID, uint16_t Resistance);
bool fault_is_aCellHighImpedance(void);
void fault_clear_aCellHighImpedance(void);

bool fault_set_wisoSPIPECError(void);
bool fault_is_wisoSPIPECError(void);
void fault_clear_wisoSPIPECError(void);

bool fault_set_wSelfTestError(void);
bool fault_is_wSelfTestError(void);
void fault_clear_wSelfTestError(void);

bool fault_set_fVehicleIdle(void);
bool fault_is_fVehicleIdle(void);
void fault_clear_fVehicleIdle(void);

bool fault_set_wInverterSDCOpenRequest(uint8_t InverterID);
bool fault_is_wInverterSDCOpenRequest(void);
void fault_clear_wInverterSDCOpenRequest(void);

bool fault_set_cVoltageFailsafeMode(void);
bool fault_is_cVoltageFailsafeMode(void);
void fault_clear_cVoltageFailsafeMode(void);

bool fault_set_cCurrentFailsafeMode(void);
bool fault_is_cCurrentFailsafeMode(void);
void fault_clear_cCurrentFailsafeMode(void);

bool fault_set_aStartupFailure(void);
bool fault_is_aStartupFailure(void);
void fault_clear_aStartupFailure(void);

bool fault_set_fChargerEnabled(void);
bool fault_is_fChargerEnabled(void);
void fault_clear_fChargerEnabled(void);

bool fault_set_wChargingTimeout(void);
bool fault_is_wChargingTimeout(void);
void fault_clear_wChargingTimeout(void);

