/**
 * This file was autogenerated using the WR dbc_to_c.py
 */

#include <stdbool.h>
#include <stdint.h>
#include "Lib_can.h"

void set_582_BMS_f027_VehicleIdle(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 6);
    }
    else
    {
        data[3] &= ~(1 << 6);
    }
}

void set_582_BMS_w017_DischargeCompleted(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 4);
    }
    else
    {
        data[2] &= ~(1 << 4);
    }
}

void set_582_BMS_a010_CellTemperatureOORL(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 5);
    }
    else
    {
        data[1] &= ~(1 << 5);
    }
}

void set_582_BMS_w002_CellUndervoltage(uint8_t data[], bool value)
{
    if (value)
    {
        data[0] |= (1 << 5);
    }
    else
    {
        data[0] &= ~(1 << 5);
    }
}

void set_582_BMS_w016_ChargeCompleted(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 3);
    }
    else
    {
        data[2] &= ~(1 << 3);
    }
}

void set_582_BMS_FaultMatrixMux(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000000001111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[0] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_582_BMS_w011_ChargerMIA(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 6);
    }
    else
    {
        data[1] &= ~(1 << 6);
    }
}

void set_582_BMS_w026_SelfTestError(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 5);
    }
    else
    {
        data[3] &= ~(1 << 5);
    }
}

void set_582_BMS_c029_VoltageFailsafeMode(uint8_t data[], bool value)
{
    if (value)
    {
        data[4] |= (1 << 0);
    }
    else
    {
        data[4] &= ~(1 << 0);
    }
}

void set_582_BMS_w014_DischargeCurrentLimitOver(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 1);
    }
    else
    {
        data[2] &= ~(1 << 1);
    }
}

void set_582_BMS_w033_ChargingTimeout(uint8_t data[], bool value)
{
    if (value)
    {
        data[4] |= (1 << 4);
    }
    else
    {
        data[4] &= ~(1 << 4);
    }
}

void set_582_BMS_w015_ChargerFault(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 2);
    }
    else
    {
        data[2] &= ~(1 << 2);
    }
}

void set_582_BMS_w007_CellTemperatureAbove60degC(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 2);
    }
    else
    {
        data[1] &= ~(1 << 2);
    }
}

void set_582_BMS_c004_CellVoltageOORL(uint8_t data[], bool value)
{
    if (value)
    {
        data[0] |= (1 << 7);
    }
    else
    {
        data[0] &= ~(1 << 7);
    }
}

void set_582_BMS_f012_ChargerConnected(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 7);
    }
    else
    {
        data[1] &= ~(1 << 7);
    }
}

void set_582_BMS_a009_CellTemperatureOORH(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 4);
    }
    else
    {
        data[1] &= ~(1 << 4);
    }
}

void set_582_BMS_f032_ChargerEnabled(uint8_t data[], bool value)
{
    if (value)
    {
        data[4] |= (1 << 3);
    }
    else
    {
        data[4] &= ~(1 << 3);
    }
}

void set_582_BMS_c003_CellVoltageOORH(uint8_t data[], bool value)
{
    if (value)
    {
        data[0] |= (1 << 6);
    }
    else
    {
        data[0] &= ~(1 << 6);
    }
}

void set_582_BMS_a024_CellHighImpedance(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 3);
    }
    else
    {
        data[3] &= ~(1 << 3);
    }
}

void set_582_BMS_w005_CellOvertemperature(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 0);
    }
    else
    {
        data[1] &= ~(1 << 0);
    }
}

void set_582_BMS_c018_CurrentSensorOORH(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 5);
    }
    else
    {
        data[2] &= ~(1 << 5);
    }
}

void set_582_BMS_a022_AuxMIA(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 1);
    }
    else
    {
        data[3] &= ~(1 << 1);
    }
}

void set_582_BMS_a020_PowerStageOpen(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 7);
    }
    else
    {
        data[2] &= ~(1 << 7);
    }
}

void set_582_BMS_w028_InverterSDCOpenRequest(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 7);
    }
    else
    {
        data[3] &= ~(1 << 7);
    }
}

void set_582_BMS_a031_StartupFailure(uint8_t data[], bool value)
{
    if (value)
    {
        data[4] |= (1 << 2);
    }
    else
    {
        data[4] &= ~(1 << 2);
    }
}

void set_582_BMS_w001_CellOvervoltage(uint8_t data[], bool value)
{
    if (value)
    {
        data[0] |= (1 << 4);
    }
    else
    {
        data[0] &= ~(1 << 4);
    }
}

void set_582_BMS_c030_CurrentFailsafeMode(uint8_t data[], bool value)
{
    if (value)
    {
        data[4] |= (1 << 1);
    }
    else
    {
        data[4] &= ~(1 << 1);
    }
}

void set_582_BMS_w013_ChargeCurrentLimitOver(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 0);
    }
    else
    {
        data[2] &= ~(1 << 0);
    }
}

void set_582_BMS_w023_PowerStageFailure(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 2);
    }
    else
    {
        data[3] &= ~(1 << 2);
    }
}

void set_582_BMS_f021_BalancingActive(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 0);
    }
    else
    {
        data[3] &= ~(1 << 0);
    }
}

void set_582_BMS_w006_CellUndertemperature(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 1);
    }
    else
    {
        data[1] &= ~(1 << 1);
    }
}

void set_582_BMS_w008_CellTemperatureLostSensors(uint8_t data[], bool value)
{
    if (value)
    {
        data[1] |= (1 << 3);
    }
    else
    {
        data[1] &= ~(1 << 3);
    }
}

void set_582_BMS_w025_isoSPIPECError(uint8_t data[], bool value)
{
    if (value)
    {
        data[3] |= (1 << 4);
    }
    else
    {
        data[3] &= ~(1 << 4);
    }
}

void set_582_BMS_c019_CurrentSensorOORL(uint8_t data[], bool value)
{
    if (value)
    {
        data[2] |= (1 << 6);
    }
    else
    {
        data[2] &= ~(1 << 6);
    }
}

void set_325_BMS_a024_Resistance(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w013_PackI(uint8_t data[], float value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[4] |= (can_value >> 0) & (AND_VAL >> 0);
    data[5] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w005_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_c003_CellVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_c018_SensorVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
    data[3] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w006_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w007_CellTemperature(uint8_t data[], int8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_c003_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_c019_SensorVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
    data[3] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_a010_SensorVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_c004_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w014_PackI(uint8_t data[], float value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[4] |= (can_value >> 0) & (AND_VAL >> 0);
    data[5] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w028_InverterID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w008_LostSensors(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w014_DischargeCurrentLimit(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
    data[3] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w002_CellVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w013_ChargeCurrentLimit(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
    data[3] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w001_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_a009_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w007_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_a009_SensorVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w002_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_a024_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w001_CellVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_FaultCode(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[0] |= (can_value >> 0) & (AND_VAL >> 0);
    data[1] |= (can_value >> 8) & (AND_VAL >> 8);
}

void set_325_BMS_w005_CellTemperature(uint8_t data[], int8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_a010_CellID(uint8_t data[], uint8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[2] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_w006_CellTemperature(uint8_t data[], int8_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000000000000011111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
}

void set_325_BMS_c004_CellVoltage(uint8_t data[], uint16_t value)
{
    const float APP_SCALE = 1;
    const float CAN_SCALE = 1;
    const uint32_t AND_VAL = 0b00000000000000001111111111111111;

    uint32_t can_value = (value * APP_SCALE / CAN_SCALE);
    data[3] |= (can_value >> 0) & (AND_VAL >> 0);
    data[4] |= (can_value >> 8) & (AND_VAL >> 8);
}

