/**
 * This file was autogenerated using the WR fault_json_to_c.py
 */

#include <stdbool.h>
#include <stdint.h>
#include "can.h"
#include "can_pack.h"
#include "fault_manager.h"


uint8_t fault_matrix_bit_flags[8];

bool set_fault_matrix_bit_active(uint32_t faultID)
{
    if(is_fault_active(faultID))
    {
        return true;
    }
    faultID--; // zero index the faults
    faultID += 4; // offset the fault index for the CAN mux
    uint8_t byte_i = faultID / 8;
    uint8_t bit_i = faultID % 8;
    fault_matrix_bit_flags[byte_i] |= 1 << bit_i;

    return false;
}


bool clear_fault_matrix_bit(uint32_t faultID)
{
    bool retVal = is_fault_active(faultID);

    faultID--;
    uint8_t byte_i = faultID / 8;
    uint8_t bit_i = faultID % 8;
    fault_matrix_bit_flags[byte_i] &= ~(1 << bit_i);

    return retVal;
}


bool is_fault_active(uint32_t faultID)
{

    faultID--;
    uint8_t byte_i = faultID / 8;
    uint8_t bit_i = faultID % 8;

    return fault_matrix_bit_flags[byte_i] & (1 << bit_i);
}


bool fault_set_wCellOvervoltage(uint8_t CellID, uint16_t CellVoltage)
{
    bool already_active = is_fault_active(W001_CELLOVERVOLTAGE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W001_CELLOVERVOLTAGE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W001_CELLOVERVOLTAGE);
        set_325_BMS_w001_CellID(data, CellID);
        set_325_BMS_w001_CellVoltage(data, CellVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellOvervoltage(void)
{
    return is_fault_active(W001_CELLOVERVOLTAGE);
}


void fault_clear_wCellOvervoltage(void)
{
    clear_fault_matrix_bit(W001_CELLOVERVOLTAGE);
}


bool fault_set_wCellUndervoltage(uint8_t CellID, uint16_t CellVoltage)
{
    bool already_active = is_fault_active(W002_CELLUNDERVOLTAGE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W002_CELLUNDERVOLTAGE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W002_CELLUNDERVOLTAGE);
        set_325_BMS_w002_CellID(data, CellID);
        set_325_BMS_w002_CellVoltage(data, CellVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellUndervoltage(void)
{
    return is_fault_active(W002_CELLUNDERVOLTAGE);
}


void fault_clear_wCellUndervoltage(void)
{
    clear_fault_matrix_bit(W002_CELLUNDERVOLTAGE);
}


bool fault_set_cCellVoltageOORH(uint8_t CellID, uint16_t CellVoltage)
{
    bool already_active = is_fault_active(C003_CELLVOLTAGEOORH);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C003_CELLVOLTAGEOORH);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C003_CELLVOLTAGEOORH);
        set_325_BMS_c003_CellID(data, CellID);
        set_325_BMS_c003_CellVoltage(data, CellVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cCellVoltageOORH(void)
{
    return is_fault_active(C003_CELLVOLTAGEOORH);
}


void fault_clear_cCellVoltageOORH(void)
{
    clear_fault_matrix_bit(C003_CELLVOLTAGEOORH);
}


bool fault_set_cCellVoltageOORL(uint8_t CellID, uint16_t CellVoltage)
{
    bool already_active = is_fault_active(C004_CELLVOLTAGEOORL);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C004_CELLVOLTAGEOORL);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C004_CELLVOLTAGEOORL);
        set_325_BMS_c004_CellID(data, CellID);
        set_325_BMS_c004_CellVoltage(data, CellVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cCellVoltageOORL(void)
{
    return is_fault_active(C004_CELLVOLTAGEOORL);
}


void fault_clear_cCellVoltageOORL(void)
{
    clear_fault_matrix_bit(C004_CELLVOLTAGEOORL);
}


bool fault_set_wCellOvertemperature(uint8_t CellID, int8_t CellTemperature)
{
    bool already_active = is_fault_active(W005_CELLOVERTEMPERATURE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W005_CELLOVERTEMPERATURE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W005_CELLOVERTEMPERATURE);
        set_325_BMS_w005_CellID(data, CellID);
        set_325_BMS_w005_CellTemperature(data, CellTemperature);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellOvertemperature(void)
{
    return is_fault_active(W005_CELLOVERTEMPERATURE);
}


void fault_clear_wCellOvertemperature(void)
{
    clear_fault_matrix_bit(W005_CELLOVERTEMPERATURE);
}


bool fault_set_wCellUndertemperature(uint8_t CellID, int8_t CellTemperature)
{
    bool already_active = is_fault_active(W006_CELLUNDERTEMPERATURE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W006_CELLUNDERTEMPERATURE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W006_CELLUNDERTEMPERATURE);
        set_325_BMS_w006_CellID(data, CellID);
        set_325_BMS_w006_CellTemperature(data, CellTemperature);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellUndertemperature(void)
{
    return is_fault_active(W006_CELLUNDERTEMPERATURE);
}


void fault_clear_wCellUndertemperature(void)
{
    clear_fault_matrix_bit(W006_CELLUNDERTEMPERATURE);
}


bool fault_set_wCellTemperatureAbove60degC(uint8_t CellID, int8_t CellTemperature)
{
    bool already_active = is_fault_active(W007_CELLTEMPERATUREABOVE60DEGC);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W007_CELLTEMPERATUREABOVE60DEGC);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W007_CELLTEMPERATUREABOVE60DEGC);
        set_325_BMS_w007_CellID(data, CellID);
        set_325_BMS_w007_CellTemperature(data, CellTemperature);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellTemperatureAbove60degC(void)
{
    return is_fault_active(W007_CELLTEMPERATUREABOVE60DEGC);
}


void fault_clear_wCellTemperatureAbove60degC(void)
{
    clear_fault_matrix_bit(W007_CELLTEMPERATUREABOVE60DEGC);
}


bool fault_set_wCellTemperatureLostSensors(uint8_t LostSensors)
{
    bool already_active = is_fault_active(W008_CELLTEMPERATURELOSTSENSORS);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W008_CELLTEMPERATURELOSTSENSORS);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W008_CELLTEMPERATURELOSTSENSORS);
        set_325_BMS_w008_LostSensors(data, LostSensors);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wCellTemperatureLostSensors(void)
{
    return is_fault_active(W008_CELLTEMPERATURELOSTSENSORS);
}


void fault_clear_wCellTemperatureLostSensors(void)
{
    clear_fault_matrix_bit(W008_CELLTEMPERATURELOSTSENSORS);
}


bool fault_set_aCellTemperatureOORH(uint8_t CellID, uint16_t SensorVoltage)
{
    bool already_active = is_fault_active(A009_CELLTEMPERATUREOORH);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A009_CELLTEMPERATUREOORH);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A009_CELLTEMPERATUREOORH);
        set_325_BMS_a009_CellID(data, CellID);
        set_325_BMS_a009_SensorVoltage(data, SensorVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aCellTemperatureOORH(void)
{
    return is_fault_active(A009_CELLTEMPERATUREOORH);
}


void fault_clear_aCellTemperatureOORH(void)
{
    clear_fault_matrix_bit(A009_CELLTEMPERATUREOORH);
}


bool fault_set_aCellTemperatureOORL(uint8_t CellID, uint16_t SensorVoltage)
{
    bool already_active = is_fault_active(A010_CELLTEMPERATUREOORL);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A010_CELLTEMPERATUREOORL);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A010_CELLTEMPERATUREOORL);
        set_325_BMS_a010_CellID(data, CellID);
        set_325_BMS_a010_SensorVoltage(data, SensorVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aCellTemperatureOORL(void)
{
    return is_fault_active(A010_CELLTEMPERATUREOORL);
}


void fault_clear_aCellTemperatureOORL(void)
{
    clear_fault_matrix_bit(A010_CELLTEMPERATUREOORL);
}


bool fault_set_wChargerMIA(void)
{
    bool already_active = is_fault_active(W011_CHARGERMIA);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W011_CHARGERMIA);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W011_CHARGERMIA);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wChargerMIA(void)
{
    return is_fault_active(W011_CHARGERMIA);
}


void fault_clear_wChargerMIA(void)
{
    clear_fault_matrix_bit(W011_CHARGERMIA);
}


bool fault_set_fChargerConnected(void)
{
    bool already_active = is_fault_active(F012_CHARGERCONNECTED);

    if(!already_active)
    {
        set_fault_matrix_bit_active(F012_CHARGERCONNECTED);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, F012_CHARGERCONNECTED);
    }

    return already_active;
}


bool fault_is_fChargerConnected(void)
{
    return is_fault_active(F012_CHARGERCONNECTED);
}


void fault_clear_fChargerConnected(void)
{
    clear_fault_matrix_bit(F012_CHARGERCONNECTED);
}


bool fault_set_wChargeCurrentLimitOver(uint16_t ChargeCurrentLimit, float PackI)
{
    bool already_active = is_fault_active(W013_CHARGECURRENTLIMITOVER);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W013_CHARGECURRENTLIMITOVER);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W013_CHARGECURRENTLIMITOVER);
        set_325_BMS_w013_ChargeCurrentLimit(data, ChargeCurrentLimit);
        set_325_BMS_w013_PackI(data, PackI);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wChargeCurrentLimitOver(void)
{
    return is_fault_active(W013_CHARGECURRENTLIMITOVER);
}


void fault_clear_wChargeCurrentLimitOver(void)
{
    clear_fault_matrix_bit(W013_CHARGECURRENTLIMITOVER);
}


bool fault_set_wDischargeCurrentLimitOver(uint16_t DischargeCurrentLimit, float PackI)
{
    bool already_active = is_fault_active(W014_DISCHARGECURRENTLIMITOVER);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W014_DISCHARGECURRENTLIMITOVER);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W014_DISCHARGECURRENTLIMITOVER);
        set_325_BMS_w014_DischargeCurrentLimit(data, DischargeCurrentLimit);
        set_325_BMS_w014_PackI(data, PackI);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wDischargeCurrentLimitOver(void)
{
    return is_fault_active(W014_DISCHARGECURRENTLIMITOVER);
}


void fault_clear_wDischargeCurrentLimitOver(void)
{
    clear_fault_matrix_bit(W014_DISCHARGECURRENTLIMITOVER);
}


bool fault_set_wChargerFault(void)
{
    bool already_active = is_fault_active(W015_CHARGERFAULT);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W015_CHARGERFAULT);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W015_CHARGERFAULT);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wChargerFault(void)
{
    return is_fault_active(W015_CHARGERFAULT);
}


void fault_clear_wChargerFault(void)
{
    clear_fault_matrix_bit(W015_CHARGERFAULT);
}


bool fault_set_wChargeCompleted(void)
{
    bool already_active = is_fault_active(W016_CHARGECOMPLETED);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W016_CHARGECOMPLETED);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W016_CHARGECOMPLETED);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wChargeCompleted(void)
{
    return is_fault_active(W016_CHARGECOMPLETED);
}


void fault_clear_wChargeCompleted(void)
{
    clear_fault_matrix_bit(W016_CHARGECOMPLETED);
}


bool fault_set_wDischargeCompleted(void)
{
    bool already_active = is_fault_active(W017_DISCHARGECOMPLETED);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W017_DISCHARGECOMPLETED);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W017_DISCHARGECOMPLETED);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wDischargeCompleted(void)
{
    return is_fault_active(W017_DISCHARGECOMPLETED);
}


void fault_clear_wDischargeCompleted(void)
{
    clear_fault_matrix_bit(W017_DISCHARGECOMPLETED);
}


bool fault_set_cCurrentSensorOORH(uint16_t SensorVoltage)
{
    bool already_active = is_fault_active(C018_CURRENTSENSOROORH);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C018_CURRENTSENSOROORH);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C018_CURRENTSENSOROORH);
        set_325_BMS_c018_SensorVoltage(data, SensorVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cCurrentSensorOORH(void)
{
    return is_fault_active(C018_CURRENTSENSOROORH);
}


void fault_clear_cCurrentSensorOORH(void)
{
    clear_fault_matrix_bit(C018_CURRENTSENSOROORH);
}


bool fault_set_cCurrentSensorOORL(uint16_t SensorVoltage)
{
    bool already_active = is_fault_active(C019_CURRENTSENSOROORL);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C019_CURRENTSENSOROORL);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C019_CURRENTSENSOROORL);
        set_325_BMS_c019_SensorVoltage(data, SensorVoltage);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cCurrentSensorOORL(void)
{
    return is_fault_active(C019_CURRENTSENSOROORL);
}


void fault_clear_cCurrentSensorOORL(void)
{
    clear_fault_matrix_bit(C019_CURRENTSENSOROORL);
}


bool fault_set_aPowerStageOpen(void)
{
    bool already_active = is_fault_active(A020_POWERSTAGEOPEN);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A020_POWERSTAGEOPEN);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A020_POWERSTAGEOPEN);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aPowerStageOpen(void)
{
    return is_fault_active(A020_POWERSTAGEOPEN);
}


void fault_clear_aPowerStageOpen(void)
{
    clear_fault_matrix_bit(A020_POWERSTAGEOPEN);
}


bool fault_set_fBalancingActive(void)
{
    bool already_active = is_fault_active(F021_BALANCINGACTIVE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(F021_BALANCINGACTIVE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, F021_BALANCINGACTIVE);
    }

    return already_active;
}


bool fault_is_fBalancingActive(void)
{
    return is_fault_active(F021_BALANCINGACTIVE);
}


void fault_clear_fBalancingActive(void)
{
    clear_fault_matrix_bit(F021_BALANCINGACTIVE);
}


bool fault_set_aAuxMIA(void)
{
    bool already_active = is_fault_active(A022_AUXMIA);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A022_AUXMIA);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A022_AUXMIA);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aAuxMIA(void)
{
    return is_fault_active(A022_AUXMIA);
}


void fault_clear_aAuxMIA(void)
{
    clear_fault_matrix_bit(A022_AUXMIA);
}


bool fault_set_wPowerStageFailure(void)
{
    bool already_active = is_fault_active(W023_POWERSTAGEFAILURE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W023_POWERSTAGEFAILURE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W023_POWERSTAGEFAILURE);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wPowerStageFailure(void)
{
    return is_fault_active(W023_POWERSTAGEFAILURE);
}


void fault_clear_wPowerStageFailure(void)
{
    clear_fault_matrix_bit(W023_POWERSTAGEFAILURE);
}


bool fault_set_aCellHighImpedance(uint8_t CellID, uint16_t Resistance)
{
    bool already_active = is_fault_active(A024_CELLHIGHIMPEDANCE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A024_CELLHIGHIMPEDANCE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A024_CELLHIGHIMPEDANCE);
        set_325_BMS_a024_CellID(data, CellID);
        set_325_BMS_a024_Resistance(data, Resistance);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aCellHighImpedance(void)
{
    return is_fault_active(A024_CELLHIGHIMPEDANCE);
}


void fault_clear_aCellHighImpedance(void)
{
    clear_fault_matrix_bit(A024_CELLHIGHIMPEDANCE);
}


bool fault_set_wisoSPIPECError(void)
{
    bool already_active = is_fault_active(W025_ISOSPIPECERROR);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W025_ISOSPIPECERROR);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W025_ISOSPIPECERROR);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wisoSPIPECError(void)
{
    return is_fault_active(W025_ISOSPIPECERROR);
}


void fault_clear_wisoSPIPECError(void)
{
    clear_fault_matrix_bit(W025_ISOSPIPECERROR);
}


bool fault_set_wSelfTestError(void)
{
    bool already_active = is_fault_active(W026_SELFTESTERROR);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W026_SELFTESTERROR);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W026_SELFTESTERROR);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wSelfTestError(void)
{
    return is_fault_active(W026_SELFTESTERROR);
}


void fault_clear_wSelfTestError(void)
{
    clear_fault_matrix_bit(W026_SELFTESTERROR);
}


bool fault_set_fVehicleIdle(void)
{
    bool already_active = is_fault_active(F027_VEHICLEIDLE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(F027_VEHICLEIDLE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, F027_VEHICLEIDLE);
    }

    return already_active;
}


bool fault_is_fVehicleIdle(void)
{
    return is_fault_active(F027_VEHICLEIDLE);
}


void fault_clear_fVehicleIdle(void)
{
    clear_fault_matrix_bit(F027_VEHICLEIDLE);
}


bool fault_set_wInverterSDCOpenRequest(uint8_t InverterID)
{
    bool already_active = is_fault_active(W028_INVERTERSDCOPENREQUEST);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W028_INVERTERSDCOPENREQUEST);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W028_INVERTERSDCOPENREQUEST);
        set_325_BMS_w028_InverterID(data, InverterID);

        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wInverterSDCOpenRequest(void)
{
    return is_fault_active(W028_INVERTERSDCOPENREQUEST);
}


void fault_clear_wInverterSDCOpenRequest(void)
{
    clear_fault_matrix_bit(W028_INVERTERSDCOPENREQUEST);
}


bool fault_set_cVoltageFailsafeMode(void)
{
    bool already_active = is_fault_active(C029_VOLTAGEFAILSAFEMODE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C029_VOLTAGEFAILSAFEMODE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C029_VOLTAGEFAILSAFEMODE);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cVoltageFailsafeMode(void)
{
    return is_fault_active(C029_VOLTAGEFAILSAFEMODE);
}


void fault_clear_cVoltageFailsafeMode(void)
{
    clear_fault_matrix_bit(C029_VOLTAGEFAILSAFEMODE);
}


bool fault_set_cCurrentFailsafeMode(void)
{
    bool already_active = is_fault_active(C030_CURRENTFAILSAFEMODE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(C030_CURRENTFAILSAFEMODE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, C030_CURRENTFAILSAFEMODE);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_cCurrentFailsafeMode(void)
{
    return is_fault_active(C030_CURRENTFAILSAFEMODE);
}


void fault_clear_cCurrentFailsafeMode(void)
{
    clear_fault_matrix_bit(C030_CURRENTFAILSAFEMODE);
}


bool fault_set_aStartupFailure(void)
{
    bool already_active = is_fault_active(A031_STARTUPFAILURE);

    if(!already_active)
    {
        set_fault_matrix_bit_active(A031_STARTUPFAILURE);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, A031_STARTUPFAILURE);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_aStartupFailure(void)
{
    return is_fault_active(A031_STARTUPFAILURE);
}


void fault_clear_aStartupFailure(void)
{
    clear_fault_matrix_bit(A031_STARTUPFAILURE);
}


bool fault_set_fChargerEnabled(void)
{
    bool already_active = is_fault_active(F032_CHARGERENABLED);

    if(!already_active)
    {
        set_fault_matrix_bit_active(F032_CHARGERENABLED);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, F032_CHARGERENABLED);
    }

    return already_active;
}


bool fault_is_fChargerEnabled(void)
{
    return is_fault_active(F032_CHARGERENABLED);
}


void fault_clear_fChargerEnabled(void)
{
    clear_fault_matrix_bit(F032_CHARGERENABLED);
}


bool fault_set_wChargingTimeout(void)
{
    bool already_active = is_fault_active(W033_CHARGINGTIMEOUT);

    if(!already_active)
    {
        set_fault_matrix_bit_active(W033_CHARGINGTIMEOUT);

        uint8_t data[8];
        set_325_BMS_FaultCode(data, W033_CHARGINGTIMEOUT);
        can_send_fault(data);
    }

    return already_active;
}


bool fault_is_wChargingTimeout(void)
{
    return is_fault_active(W033_CHARGINGTIMEOUT);
}


void fault_clear_wChargingTimeout(void)
{
    clear_fault_matrix_bit(W033_CHARGINGTIMEOUT);
}


